// <copyright file="AccountFilter.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// AccountFilter.
    /// </summary>
    public class AccountFilter
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountFilter"/> class.
        /// </summary>
        public AccountFilter()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountFilter"/> class.
        /// </summary>
        /// <param name="depository">depository.</param>
        /// <param name="credit">credit.</param>
        /// <param name="loan">loan.</param>
        /// <param name="investment">investment.</param>
        public AccountFilter(
            List<string> depository = null,
            List<string> credit = null,
            List<string> loan = null,
            List<string> investment = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Depository = depository;
            this.Credit = credit;
            this.Loan = loan;
            this.Investment = investment;
        }

        /// <summary>
        /// A list of account subtypes to be filtered.
        /// </summary>
        [JsonProperty("depository", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Depository { get; set; }

        /// <summary>
        /// A list of account subtypes to be filtered.
        /// </summary>
        [JsonProperty("credit", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Credit { get; set; }

        /// <summary>
        /// A list of account subtypes to be filtered.
        /// </summary>
        [JsonProperty("loan", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Loan { get; set; }

        /// <summary>
        /// A list of account subtypes to be filtered.
        /// </summary>
        [JsonProperty("investment", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Investment { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccountFilter : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AccountFilter other &&
                (this.Depository == null && other.Depository == null ||
                 this.Depository?.Equals(other.Depository) == true) &&
                (this.Credit == null && other.Credit == null ||
                 this.Credit?.Equals(other.Credit) == true) &&
                (this.Loan == null && other.Loan == null ||
                 this.Loan?.Equals(other.Loan) == true) &&
                (this.Investment == null && other.Investment == null ||
                 this.Investment?.Equals(other.Investment) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Depository = {(this.Depository == null ? "null" : $"[{string.Join(", ", this.Depository)} ]")}");
            toStringOutput.Add($"Credit = {(this.Credit == null ? "null" : $"[{string.Join(", ", this.Credit)} ]")}");
            toStringOutput.Add($"Loan = {(this.Loan == null ? "null" : $"[{string.Join(", ", this.Loan)} ]")}");
            toStringOutput.Add($"Investment = {(this.Investment == null ? "null" : $"[{string.Join(", ", this.Investment)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}