// <copyright file="AccountSubtype.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// AccountSubtype.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum AccountSubtype
    {
        /// <summary>
        /// Enum401A.
        /// </summary>
        [EnumMember(Value = "401a")]
        Enum401A,

        /// <summary>
        /// Enum401K.
        /// </summary>
        [EnumMember(Value = "401k")]
        Enum401K,

        /// <summary>
        /// Enum403B.
        /// </summary>
        [EnumMember(Value = "403B")]
        Enum403B,

        /// <summary>
        /// Enum457B.
        /// </summary>
        [EnumMember(Value = "457b")]
        Enum457B,

        /// <summary>
        /// Enum529.
        /// </summary>
        [EnumMember(Value = "529")]
        Enum529,

        /// <summary>
        /// Brokerage.
        /// </summary>
        [EnumMember(Value = "brokerage")]
        Brokerage,

        /// <summary>
        /// EnumCashIsa.
        /// </summary>
        [EnumMember(Value = "cash isa")]
        EnumCashIsa,

        /// <summary>
        /// EnumEducationSavingsAccount.
        /// </summary>
        [EnumMember(Value = "education savings account")]
        EnumEducationSavingsAccount,

        /// <summary>
        /// Ebt.
        /// </summary>
        [EnumMember(Value = "ebt")]
        Ebt,

        /// <summary>
        /// EnumFixedAnnuity.
        /// </summary>
        [EnumMember(Value = "fixed annuity")]
        EnumFixedAnnuity,

        /// <summary>
        /// Gic.
        /// </summary>
        [EnumMember(Value = "gic")]
        Gic,

        /// <summary>
        /// EnumHealthReimbursementArrangement.
        /// </summary>
        [EnumMember(Value = "health reimbursement arrangement")]
        EnumHealthReimbursementArrangement,

        /// <summary>
        /// Hsa.
        /// </summary>
        [EnumMember(Value = "hsa")]
        Hsa,

        /// <summary>
        /// Isa.
        /// </summary>
        [EnumMember(Value = "isa")]
        Isa,

        /// <summary>
        /// Ira.
        /// </summary>
        [EnumMember(Value = "ira")]
        Ira,

        /// <summary>
        /// Lif.
        /// </summary>
        [EnumMember(Value = "lif")]
        Lif,

        /// <summary>
        /// EnumLifeInsurance.
        /// </summary>
        [EnumMember(Value = "life insurance")]
        EnumLifeInsurance,

        /// <summary>
        /// Lira.
        /// </summary>
        [EnumMember(Value = "lira")]
        Lira,

        /// <summary>
        /// Lrif.
        /// </summary>
        [EnumMember(Value = "lrif")]
        Lrif,

        /// <summary>
        /// Lrsp.
        /// </summary>
        [EnumMember(Value = "lrsp")]
        Lrsp,

        /// <summary>
        /// EnumNontaxableBrokerageAccount.
        /// </summary>
        [EnumMember(Value = "non-taxable brokerage account")]
        EnumNontaxableBrokerageAccount,

        /// <summary>
        /// Other.
        /// </summary>
        [EnumMember(Value = "other")]
        Other,

        /// <summary>
        /// EnumOtherInsurance.
        /// </summary>
        [EnumMember(Value = "other insurance")]
        EnumOtherInsurance,

        /// <summary>
        /// EnumOtherAnnuity.
        /// </summary>
        [EnumMember(Value = "other annuity")]
        EnumOtherAnnuity,

        /// <summary>
        /// Prif.
        /// </summary>
        [EnumMember(Value = "prif")]
        Prif,

        /// <summary>
        /// Rdsp.
        /// </summary>
        [EnumMember(Value = "rdsp")]
        Rdsp,

        /// <summary>
        /// Resp.
        /// </summary>
        [EnumMember(Value = "resp")]
        Resp,

        /// <summary>
        /// Rlif.
        /// </summary>
        [EnumMember(Value = "rlif")]
        Rlif,

        /// <summary>
        /// Rrif.
        /// </summary>
        [EnumMember(Value = "rrif")]
        Rrif,

        /// <summary>
        /// Pension.
        /// </summary>
        [EnumMember(Value = "pension")]
        Pension,

        /// <summary>
        /// EnumProfitSharingPlan.
        /// </summary>
        [EnumMember(Value = "profit sharing plan")]
        EnumProfitSharingPlan,

        /// <summary>
        /// Retirement.
        /// </summary>
        [EnumMember(Value = "retirement")]
        Retirement,

        /// <summary>
        /// Roth.
        /// </summary>
        [EnumMember(Value = "roth")]
        Roth,

        /// <summary>
        /// EnumRoth401K.
        /// </summary>
        [EnumMember(Value = "roth 401k")]
        EnumRoth401K,

        /// <summary>
        /// Rrsp.
        /// </summary>
        [EnumMember(Value = "rrsp")]
        Rrsp,

        /// <summary>
        /// EnumSepIra.
        /// </summary>
        [EnumMember(Value = "sep ira")]
        EnumSepIra,

        /// <summary>
        /// EnumSimpleIra.
        /// </summary>
        [EnumMember(Value = "simple ira")]
        EnumSimpleIra,

        /// <summary>
        /// Sipp.
        /// </summary>
        [EnumMember(Value = "sipp")]
        Sipp,

        /// <summary>
        /// EnumStockPlan.
        /// </summary>
        [EnumMember(Value = "stock plan")]
        EnumStockPlan,

        /// <summary>
        /// EnumThriftSavingsPlan.
        /// </summary>
        [EnumMember(Value = "thrift savings plan")]
        EnumThriftSavingsPlan,

        /// <summary>
        /// Tfsa.
        /// </summary>
        [EnumMember(Value = "tfsa")]
        Tfsa,

        /// <summary>
        /// Trust.
        /// </summary>
        [EnumMember(Value = "trust")]
        Trust,

        /// <summary>
        /// Ugma.
        /// </summary>
        [EnumMember(Value = "ugma")]
        Ugma,

        /// <summary>
        /// Utma.
        /// </summary>
        [EnumMember(Value = "utma")]
        Utma,

        /// <summary>
        /// EnumVariableAnnuity.
        /// </summary>
        [EnumMember(Value = "variable annuity")]
        EnumVariableAnnuity,

        /// <summary>
        /// EnumCreditCard.
        /// </summary>
        [EnumMember(Value = "credit card")]
        EnumCreditCard,

        /// <summary>
        /// Paypal.
        /// </summary>
        [EnumMember(Value = "paypal")]
        Paypal,

        /// <summary>
        /// Cd.
        /// </summary>
        [EnumMember(Value = "cd")]
        Cd,

        /// <summary>
        /// Checking.
        /// </summary>
        [EnumMember(Value = "checking")]
        Checking,

        /// <summary>
        /// Savings.
        /// </summary>
        [EnumMember(Value = "savings")]
        Savings,

        /// <summary>
        /// EnumMoneyMarket.
        /// </summary>
        [EnumMember(Value = "money market")]
        EnumMoneyMarket,

        /// <summary>
        /// Prepaid.
        /// </summary>
        [EnumMember(Value = "prepaid")]
        Prepaid,

        /// <summary>
        /// Auto.
        /// </summary>
        [EnumMember(Value = "auto")]
        Auto,

        /// <summary>
        /// Business.
        /// </summary>
        [EnumMember(Value = "business")]
        Business,

        /// <summary>
        /// Commercial.
        /// </summary>
        [EnumMember(Value = "commercial")]
        Commercial,

        /// <summary>
        /// Construction.
        /// </summary>
        [EnumMember(Value = "construction")]
        Construction,

        /// <summary>
        /// Consumer.
        /// </summary>
        [EnumMember(Value = "consumer")]
        Consumer,

        /// <summary>
        /// Home.
        /// </summary>
        [EnumMember(Value = "home")]
        Home,

        /// <summary>
        /// EnumHomeEquity.
        /// </summary>
        [EnumMember(Value = "home equity")]
        EnumHomeEquity,

        /// <summary>
        /// Loan.
        /// </summary>
        [EnumMember(Value = "loan")]
        Loan,

        /// <summary>
        /// Mortgage.
        /// </summary>
        [EnumMember(Value = "mortgage")]
        Mortgage,

        /// <summary>
        /// Overdraft.
        /// </summary>
        [EnumMember(Value = "overdraft")]
        Overdraft,

        /// <summary>
        /// EnumLineOfCredit.
        /// </summary>
        [EnumMember(Value = "line of credit")]
        EnumLineOfCredit,

        /// <summary>
        /// Student.
        /// </summary>
        [EnumMember(Value = "student")]
        Student,

        /// <summary>
        /// EnumCashManagement.
        /// </summary>
        [EnumMember(Value = "cash management")]
        EnumCashManagement,

        /// <summary>
        /// Keogh.
        /// </summary>
        [EnumMember(Value = "keogh")]
        Keogh,

        /// <summary>
        /// EnumMutualFund.
        /// </summary>
        [EnumMember(Value = "mutual fund")]
        EnumMutualFund,

        /// <summary>
        /// Recurring.
        /// </summary>
        [EnumMember(Value = "recurring")]
        Recurring,

        /// <summary>
        /// Rewards.
        /// </summary>
        [EnumMember(Value = "rewards")]
        Rewards,

        /// <summary>
        /// EnumSafeDeposit.
        /// </summary>
        [EnumMember(Value = "safe deposit")]
        EnumSafeDeposit,

        /// <summary>
        /// Sarsep.
        /// </summary>
        [EnumMember(Value = "sarsep")]
        Sarsep,

        /// <summary>
        /// Payroll.
        /// </summary>
        [EnumMember(Value = "payroll")]
        Payroll,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}