// <copyright file="AssetReportUser.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// AssetReportUser.
    /// </summary>
    public class AssetReportUser
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string clientUserId;
        private string firstName;
        private string middleName;
        private string lastName;
        private string ssn;
        private string phoneNumber;
        private string email;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "client_user_id", false },
            { "first_name", false },
            { "middle_name", false },
            { "last_name", false },
            { "ssn", false },
            { "phone_number", false },
            { "email", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetReportUser"/> class.
        /// </summary>
        public AssetReportUser()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetReportUser"/> class.
        /// </summary>
        /// <param name="clientUserId">client_user_id.</param>
        /// <param name="firstName">first_name.</param>
        /// <param name="middleName">middle_name.</param>
        /// <param name="lastName">last_name.</param>
        /// <param name="ssn">ssn.</param>
        /// <param name="phoneNumber">phone_number.</param>
        /// <param name="email">email.</param>
        public AssetReportUser(
            string clientUserId = null,
            string firstName = null,
            string middleName = null,
            string lastName = null,
            string ssn = null,
            string phoneNumber = null,
            string email = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (clientUserId != null)
            {
                this.ClientUserId = clientUserId;
            }

            if (firstName != null)
            {
                this.FirstName = firstName;
            }

            if (middleName != null)
            {
                this.MiddleName = middleName;
            }

            if (lastName != null)
            {
                this.LastName = lastName;
            }

            if (ssn != null)
            {
                this.Ssn = ssn;
            }

            if (phoneNumber != null)
            {
                this.PhoneNumber = phoneNumber;
            }

            if (email != null)
            {
                this.Email = email;
            }
        }

        /// <summary>
        /// An identifier you determine and submit for the user.
        /// </summary>
        [JsonProperty("client_user_id")]
        public string ClientUserId
        {
            get
            {
                return this.clientUserId;
            }

            set
            {
                this.shouldSerialize["client_user_id"] = true;
                this.clientUserId = value;
            }
        }

        /// <summary>
        /// The user's first name. Required for the Fannie Mae Day 1 Certainty™ program.
        /// </summary>
        [JsonProperty("first_name")]
        public string FirstName
        {
            get
            {
                return this.firstName;
            }

            set
            {
                this.shouldSerialize["first_name"] = true;
                this.firstName = value;
            }
        }

        /// <summary>
        /// The user's middle name
        /// </summary>
        [JsonProperty("middle_name")]
        public string MiddleName
        {
            get
            {
                return this.middleName;
            }

            set
            {
                this.shouldSerialize["middle_name"] = true;
                this.middleName = value;
            }
        }

        /// <summary>
        /// The user's last name.  Required for the Fannie Mae Day 1 Certainty™ program.
        /// </summary>
        [JsonProperty("last_name")]
        public string LastName
        {
            get
            {
                return this.lastName;
            }

            set
            {
                this.shouldSerialize["last_name"] = true;
                this.lastName = value;
            }
        }

        /// <summary>
        /// The user's Social Security Number. Required for the Fannie Mae Day 1 Certainty™ program.
        /// Format: "ddd-dd-dddd"
        /// </summary>
        [JsonProperty("ssn")]
        public string Ssn
        {
            get
            {
                return this.ssn;
            }

            set
            {
                this.shouldSerialize["ssn"] = true;
                this.ssn = value;
            }
        }

        /// <summary>
        /// The user's phone number, in E.164 format: +{countrycode}{number}. For example: "+14151234567". Phone numbers provided in other formats will be parsed on a best-effort basis.
        /// </summary>
        [JsonProperty("phone_number")]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumber;
            }

            set
            {
                this.shouldSerialize["phone_number"] = true;
                this.phoneNumber = value;
            }
        }

        /// <summary>
        /// The user's email address.
        /// </summary>
        [JsonProperty("email")]
        public string Email
        {
            get
            {
                return this.email;
            }

            set
            {
                this.shouldSerialize["email"] = true;
                this.email = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AssetReportUser : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetClientUserId()
        {
            this.shouldSerialize["client_user_id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFirstName()
        {
            this.shouldSerialize["first_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMiddleName()
        {
            this.shouldSerialize["middle_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLastName()
        {
            this.shouldSerialize["last_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSsn()
        {
            this.shouldSerialize["ssn"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPhoneNumber()
        {
            this.shouldSerialize["phone_number"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEmail()
        {
            this.shouldSerialize["email"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeClientUserId()
        {
            return this.shouldSerialize["client_user_id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFirstName()
        {
            return this.shouldSerialize["first_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMiddleName()
        {
            return this.shouldSerialize["middle_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLastName()
        {
            return this.shouldSerialize["last_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSsn()
        {
            return this.shouldSerialize["ssn"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePhoneNumber()
        {
            return this.shouldSerialize["phone_number"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEmail()
        {
            return this.shouldSerialize["email"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AssetReportUser other &&
                (this.ClientUserId == null && other.ClientUserId == null ||
                 this.ClientUserId?.Equals(other.ClientUserId) == true) &&
                (this.FirstName == null && other.FirstName == null ||
                 this.FirstName?.Equals(other.FirstName) == true) &&
                (this.MiddleName == null && other.MiddleName == null ||
                 this.MiddleName?.Equals(other.MiddleName) == true) &&
                (this.LastName == null && other.LastName == null ||
                 this.LastName?.Equals(other.LastName) == true) &&
                (this.Ssn == null && other.Ssn == null ||
                 this.Ssn?.Equals(other.Ssn) == true) &&
                (this.PhoneNumber == null && other.PhoneNumber == null ||
                 this.PhoneNumber?.Equals(other.PhoneNumber) == true) &&
                (this.Email == null && other.Email == null ||
                 this.Email?.Equals(other.Email) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ClientUserId = {this.ClientUserId ?? "null"}");
            toStringOutput.Add($"FirstName = {this.FirstName ?? "null"}");
            toStringOutput.Add($"MiddleName = {this.MiddleName ?? "null"}");
            toStringOutput.Add($"LastName = {this.LastName ?? "null"}");
            toStringOutput.Add($"Ssn = {this.Ssn ?? "null"}");
            toStringOutput.Add($"PhoneNumber = {this.PhoneNumber ?? "null"}");
            toStringOutput.Add($"Email = {this.Email ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}