// <copyright file="AssetReportRefreshRequestOptions.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// AssetReportRefreshRequestOptions.
    /// </summary>
    public class AssetReportRefreshRequestOptions
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetReportRefreshRequestOptions"/> class.
        /// </summary>
        public AssetReportRefreshRequestOptions()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetReportRefreshRequestOptions"/> class.
        /// </summary>
        /// <param name="clientReportId">client_report_id.</param>
        /// <param name="webhook">webhook.</param>
        /// <param name="user">user.</param>
        public AssetReportRefreshRequestOptions(
            string clientReportId = null,
            string webhook = null,
            Models.AssetReportUser user = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ClientReportId = clientReportId;
            this.Webhook = webhook;
            this.User = user;
        }

        /// <summary>
        /// Client-generated identifier, which can be used by lenders to track loan applications.
        /// </summary>
        [JsonProperty("client_report_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ClientReportId { get; set; }

        /// <summary>
        /// URL to which Plaid will send Assets webhooks, for example when the requested Asset Report is ready.
        /// </summary>
        [JsonProperty("webhook", NullValueHandling = NullValueHandling.Ignore)]
        public string Webhook { get; set; }

        /// <summary>
        /// The user object allows you to provide additional information about the user to be appended to the Asset Report. All fields are optional. The `first_name`, `last_name`, and `ssn` fields are required if you would like the Report to be eligible for Fannie Mae’s Day 1 Certainty™ program.
        /// </summary>
        [JsonProperty("user", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AssetReportUser User { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AssetReportRefreshRequestOptions : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AssetReportRefreshRequestOptions other &&
                (this.ClientReportId == null && other.ClientReportId == null ||
                 this.ClientReportId?.Equals(other.ClientReportId) == true) &&
                (this.Webhook == null && other.Webhook == null ||
                 this.Webhook?.Equals(other.Webhook) == true) &&
                (this.User == null && other.User == null ||
                 this.User?.Equals(other.User) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ClientReportId = {this.ClientReportId ?? "null"}");
            toStringOutput.Add($"Webhook = {this.Webhook ?? "null"}");
            toStringOutput.Add($"User = {(this.User == null ? "null" : this.User.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}