// <copyright file="AssetReportItem.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// AssetReportItem.
    /// </summary>
    public class AssetReportItem
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetReportItem"/> class.
        /// </summary>
        public AssetReportItem()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetReportItem"/> class.
        /// </summary>
        /// <param name="itemId">item_id.</param>
        /// <param name="institutionName">institution_name.</param>
        /// <param name="institutionId">institution_id.</param>
        /// <param name="dateLastUpdated">date_last_updated.</param>
        /// <param name="accounts">accounts.</param>
        public AssetReportItem(
            string itemId,
            string institutionName,
            string institutionId,
            DateTime dateLastUpdated,
            List<Models.AccountAssets> accounts)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ItemId = itemId;
            this.InstitutionName = institutionName;
            this.InstitutionId = institutionId;
            this.DateLastUpdated = dateLastUpdated;
            this.Accounts = accounts;
        }

        /// <summary>
        /// The `item_id` of the Item associated with this webhook, warning, or error
        /// </summary>
        [JsonProperty("item_id")]
        public string ItemId { get; set; }

        /// <summary>
        /// The full financial institution name associated with the Item.
        /// </summary>
        [JsonProperty("institution_name")]
        public string InstitutionName { get; set; }

        /// <summary>
        /// The id of the financial institution associated with the Item.
        /// </summary>
        [JsonProperty("institution_id")]
        public string InstitutionId { get; set; }

        /// <summary>
        /// The date and time when this Item’s data was last retrieved from the financial institution, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_last_updated")]
        public DateTime DateLastUpdated { get; set; }

        /// <summary>
        /// Data about each of the accounts open on the Item.
        /// </summary>
        [JsonProperty("accounts")]
        public List<Models.AccountAssets> Accounts { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AssetReportItem : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AssetReportItem other &&
                (this.ItemId == null && other.ItemId == null ||
                 this.ItemId?.Equals(other.ItemId) == true) &&
                (this.InstitutionName == null && other.InstitutionName == null ||
                 this.InstitutionName?.Equals(other.InstitutionName) == true) &&
                (this.InstitutionId == null && other.InstitutionId == null ||
                 this.InstitutionId?.Equals(other.InstitutionId) == true) &&
                (this.DateLastUpdated.Equals(other.DateLastUpdated)) &&
                (this.Accounts == null && other.Accounts == null ||
                 this.Accounts?.Equals(other.Accounts) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ItemId = {this.ItemId ?? "null"}");
            toStringOutput.Add($"InstitutionName = {this.InstitutionName ?? "null"}");
            toStringOutput.Add($"InstitutionId = {this.InstitutionId ?? "null"}");
            toStringOutput.Add($"DateLastUpdated = {this.DateLastUpdated}");
            toStringOutput.Add($"Accounts = {(this.Accounts == null ? "null" : $"[{string.Join(", ", this.Accounts)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}