// <copyright file="CanonicalDescription.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// CanonicalDescription.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum CanonicalDescription
    {
        /// <summary>
        /// Bonus.
        /// </summary>
        [EnumMember(Value = "BONUS")]
        Bonus,

        /// <summary>
        /// Commission.
        /// </summary>
        [EnumMember(Value = "COMMISSION")]
        Commission,

        /// <summary>
        /// Overtime.
        /// </summary>
        [EnumMember(Value = "OVERTIME")]
        Overtime,

        /// <summary>
        /// EnumPaidTimeOff.
        /// </summary>
        [EnumMember(Value = "PAID TIME OFF")]
        EnumPaidTimeOff,

        /// <summary>
        /// EnumRegularPay.
        /// </summary>
        [EnumMember(Value = "REGULAR PAY")]
        EnumRegularPay,

        /// <summary>
        /// Vacation.
        /// </summary>
        [EnumMember(Value = "VACATION")]
        Vacation,

        /// <summary>
        /// EnumEmployeeMedicare.
        /// </summary>
        [EnumMember(Value = "EMPLOYEE MEDICARE")]
        EnumEmployeeMedicare,

        /// <summary>
        /// Fica.
        /// </summary>
        [EnumMember(Value = "FICA")]
        Fica,

        /// <summary>
        /// EnumSocialSecurityEmployeeTax.
        /// </summary>
        [EnumMember(Value = "SOCIAL SECURITY EMPLOYEE TAX")]
        EnumSocialSecurityEmployeeTax,

        /// <summary>
        /// Medical.
        /// </summary>
        [EnumMember(Value = "MEDICAL")]
        Medical,

        /// <summary>
        /// Vision.
        /// </summary>
        [EnumMember(Value = "VISION")]
        Vision,

        /// <summary>
        /// Dental.
        /// </summary>
        [EnumMember(Value = "DENTAL")]
        Dental,

        /// <summary>
        /// EnumNetPay.
        /// </summary>
        [EnumMember(Value = "NET PAY")]
        EnumNetPay,

        /// <summary>
        /// Taxes.
        /// </summary>
        [EnumMember(Value = "TAXES")]
        Taxes,

        /// <summary>
        /// NotFound.
        /// </summary>
        [EnumMember(Value = "NOT_FOUND")]
        NotFound,

        /// <summary>
        /// Other.
        /// </summary>
        [EnumMember(Value = "OTHER")]
        Other,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}