// <copyright file="CreditCardLiability.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// CreditCardLiability.
    /// </summary>
    public class CreditCardLiability
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreditCardLiability"/> class.
        /// </summary>
        public CreditCardLiability()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreditCardLiability"/> class.
        /// </summary>
        /// <param name="aprs">aprs.</param>
        /// <param name="lastPaymentAmount">last_payment_amount.</param>
        /// <param name="lastPaymentDate">last_payment_date.</param>
        /// <param name="lastStatementIssueDate">last_statement_issue_date.</param>
        /// <param name="minimumPaymentAmount">minimum_payment_amount.</param>
        /// <param name="accountId">account_id.</param>
        /// <param name="isOverdue">is_overdue.</param>
        /// <param name="nextPaymentDueDate">next_payment_due_date.</param>
        public CreditCardLiability(
            List<Models.Apr> aprs,
            double lastPaymentAmount,
            DateTime lastPaymentDate,
            DateTime lastStatementIssueDate,
            double minimumPaymentAmount,
            string accountId = null,
            bool? isOverdue = null,
            DateTime? nextPaymentDueDate = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.AccountId = accountId;
            this.Aprs = aprs;
            this.IsOverdue = isOverdue;
            this.LastPaymentAmount = lastPaymentAmount;
            this.LastPaymentDate = lastPaymentDate;
            this.LastStatementIssueDate = lastStatementIssueDate;
            this.MinimumPaymentAmount = minimumPaymentAmount;
            this.NextPaymentDueDate = nextPaymentDueDate;
        }

        /// <summary>
        /// The ID of the account that this liability belongs to.
        /// </summary>
        [JsonProperty("account_id", NullValueHandling = NullValueHandling.Include)]
        public string AccountId { get; set; }

        /// <summary>
        /// The various interest rates that apply to the account.
        /// </summary>
        [JsonProperty("aprs")]
        public List<Models.Apr> Aprs { get; set; }

        /// <summary>
        /// true if a payment is currently overdue. Availability for this field is limited.
        /// </summary>
        [JsonProperty("is_overdue", NullValueHandling = NullValueHandling.Include)]
        public bool? IsOverdue { get; set; }

        /// <summary>
        /// The amount of the last payment.
        /// </summary>
        [JsonProperty("last_payment_amount")]
        public double LastPaymentAmount { get; set; }

        /// <summary>
        /// The date of the last payment. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD). Availability for this field is limited.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("last_payment_date")]
        public DateTime LastPaymentDate { get; set; }

        /// <summary>
        /// The date of the last statement. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("last_statement_issue_date")]
        public DateTime LastStatementIssueDate { get; set; }

        /// <summary>
        /// The minimum payment due for the next billing cycle.
        /// </summary>
        [JsonProperty("minimum_payment_amount")]
        public double MinimumPaymentAmount { get; set; }

        /// <summary>
        /// The due date for the next payment. The due date is `null` if a payment is not expected. Dates are returned in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD).
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("next_payment_due_date", NullValueHandling = NullValueHandling.Include)]
        public DateTime? NextPaymentDueDate { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CreditCardLiability : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is CreditCardLiability other &&
                (this.AccountId == null && other.AccountId == null ||
                 this.AccountId?.Equals(other.AccountId) == true) &&
                (this.Aprs == null && other.Aprs == null ||
                 this.Aprs?.Equals(other.Aprs) == true) &&
                (this.IsOverdue == null && other.IsOverdue == null ||
                 this.IsOverdue?.Equals(other.IsOverdue) == true) &&
                (this.LastPaymentAmount.Equals(other.LastPaymentAmount)) &&
                (this.LastPaymentDate.Equals(other.LastPaymentDate)) &&
                (this.LastStatementIssueDate.Equals(other.LastStatementIssueDate)) &&
                (this.MinimumPaymentAmount.Equals(other.MinimumPaymentAmount)) &&
                (this.NextPaymentDueDate == null && other.NextPaymentDueDate == null ||
                 this.NextPaymentDueDate?.Equals(other.NextPaymentDueDate) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountId = {this.AccountId ?? "null"}");
            toStringOutput.Add($"Aprs = {(this.Aprs == null ? "null" : $"[{string.Join(", ", this.Aprs)} ]")}");
            toStringOutput.Add($"IsOverdue = {(this.IsOverdue == null ? "null" : this.IsOverdue.ToString())}");
            toStringOutput.Add($"LastPaymentAmount = {this.LastPaymentAmount}");
            toStringOutput.Add($"LastPaymentDate = {this.LastPaymentDate}");
            toStringOutput.Add($"LastStatementIssueDate = {this.LastStatementIssueDate}");
            toStringOutput.Add($"MinimumPaymentAmount = {this.MinimumPaymentAmount}");
            toStringOutput.Add($"NextPaymentDueDate = {(this.NextPaymentDueDate == null ? "null" : this.NextPaymentDueDate.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}