// <copyright file="DepositSwitchAltCreateRequest.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// DepositSwitchAltCreateRequest.
    /// </summary>
    public class DepositSwitchAltCreateRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DepositSwitchAltCreateRequest"/> class.
        /// </summary>
        public DepositSwitchAltCreateRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DepositSwitchAltCreateRequest"/> class.
        /// </summary>
        /// <param name="targetAccount">target_account.</param>
        /// <param name="targetUser">target_user.</param>
        /// <param name="clientId">client_id.</param>
        /// <param name="secret">secret.</param>
        /// <param name="options">options.</param>
        /// <param name="countryCode">country_code.</param>
        public DepositSwitchAltCreateRequest(
            Models.DepositSwitchTargetAccount targetAccount,
            Models.DepositSwitchTargetUser targetUser,
            string clientId = null,
            string secret = null,
            Models.DepositSwitchCreateRequestOptions options = null,
            Models.CountryCode1? countryCode = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ClientId = clientId;
            this.Secret = secret;
            this.TargetAccount = targetAccount;
            this.TargetUser = targetUser;
            this.Options = options;
            this.CountryCode = countryCode;
        }

        /// <summary>
        /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
        /// </summary>
        [JsonProperty("client_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ClientId { get; set; }

        /// <summary>
        /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
        /// </summary>
        [JsonProperty("secret", NullValueHandling = NullValueHandling.Ignore)]
        public string Secret { get; set; }

        /// <summary>
        /// Gets or sets TargetAccount.
        /// </summary>
        [JsonProperty("target_account")]
        public Models.DepositSwitchTargetAccount TargetAccount { get; set; }

        /// <summary>
        /// Gets or sets TargetUser.
        /// </summary>
        [JsonProperty("target_user")]
        public Models.DepositSwitchTargetUser TargetUser { get; set; }

        /// <summary>
        /// Options to configure the `/deposit_switch/create` request. If provided, cannot be `null`.
        /// </summary>
        [JsonProperty("options", NullValueHandling = NullValueHandling.Ignore)]
        public Models.DepositSwitchCreateRequestOptions Options { get; set; }

        /// <summary>
        /// ISO-3166-1 alpha-2 country code standard.
        /// </summary>
        [JsonProperty("country_code", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CountryCode1? CountryCode { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"DepositSwitchAltCreateRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is DepositSwitchAltCreateRequest other &&
                (this.ClientId == null && other.ClientId == null ||
                 this.ClientId?.Equals(other.ClientId) == true) &&
                (this.Secret == null && other.Secret == null ||
                 this.Secret?.Equals(other.Secret) == true) &&
                (this.TargetAccount == null && other.TargetAccount == null ||
                 this.TargetAccount?.Equals(other.TargetAccount) == true) &&
                (this.TargetUser == null && other.TargetUser == null ||
                 this.TargetUser?.Equals(other.TargetUser) == true) &&
                (this.Options == null && other.Options == null ||
                 this.Options?.Equals(other.Options) == true) &&
                (this.CountryCode == null && other.CountryCode == null ||
                 this.CountryCode?.Equals(other.CountryCode) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ClientId = {this.ClientId ?? "null"}");
            toStringOutput.Add($"Secret = {this.Secret ?? "null"}");
            toStringOutput.Add($"TargetAccount = {(this.TargetAccount == null ? "null" : this.TargetAccount.ToString())}");
            toStringOutput.Add($"TargetUser = {(this.TargetUser == null ? "null" : this.TargetUser.ToString())}");
            toStringOutput.Add($"Options = {(this.Options == null ? "null" : this.Options.ToString())}");
            toStringOutput.Add($"CountryCode = {(this.CountryCode == null ? "null" : this.CountryCode.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}