// <copyright file="EarningsTotal.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// EarningsTotal.
    /// </summary>
    public class EarningsTotal
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string description;
        private string currentHours;
        private string currentRate;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "description", false },
            { "current_hours", false },
            { "current_rate", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="EarningsTotal"/> class.
        /// </summary>
        public EarningsTotal()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EarningsTotal"/> class.
        /// </summary>
        /// <param name="canonicalDescription">canonical_description.</param>
        /// <param name="description">description.</param>
        /// <param name="currentPay">current_pay.</param>
        /// <param name="ytdPay">ytd_pay.</param>
        /// <param name="currentHours">current_hours.</param>
        /// <param name="currentRate">current_rate.</param>
        public EarningsTotal(
            Models.CanonicalDescription? canonicalDescription = null,
            string description = null,
            Models.Pay currentPay = null,
            Models.Pay ytdPay = null,
            string currentHours = null,
            string currentRate = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.CanonicalDescription = canonicalDescription;

            if (description != null)
            {
                this.Description = description;
            }
            this.CurrentPay = currentPay;
            this.YtdPay = ytdPay;

            if (currentHours != null)
            {
                this.CurrentHours = currentHours;
            }

            if (currentRate != null)
            {
                this.CurrentRate = currentRate;
            }
        }

        /// <summary>
        /// Commonly used term to describe the line item.
        /// </summary>
        [JsonProperty("canonical_description", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CanonicalDescription? CanonicalDescription { get; set; }

        /// <summary>
        /// Text of the line item as printed on the paystub.
        /// </summary>
        [JsonProperty("description")]
        public string Description
        {
            get
            {
                return this.description;
            }

            set
            {
                this.shouldSerialize["description"] = true;
                this.description = value;
            }
        }

        /// <summary>
        /// An object representing a monetary amount.
        /// </summary>
        [JsonProperty("current_pay", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Pay CurrentPay { get; set; }

        /// <summary>
        /// An object representing a monetary amount.
        /// </summary>
        [JsonProperty("ytd_pay", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Pay YtdPay { get; set; }

        /// <summary>
        /// Gets or sets CurrentHours.
        /// </summary>
        [JsonProperty("current_hours")]
        public string CurrentHours
        {
            get
            {
                return this.currentHours;
            }

            set
            {
                this.shouldSerialize["current_hours"] = true;
                this.currentHours = value;
            }
        }

        /// <summary>
        /// Gets or sets CurrentRate.
        /// </summary>
        [JsonProperty("current_rate")]
        public string CurrentRate
        {
            get
            {
                return this.currentRate;
            }

            set
            {
                this.shouldSerialize["current_rate"] = true;
                this.currentRate = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"EarningsTotal : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDescription()
        {
            this.shouldSerialize["description"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCurrentHours()
        {
            this.shouldSerialize["current_hours"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCurrentRate()
        {
            this.shouldSerialize["current_rate"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDescription()
        {
            return this.shouldSerialize["description"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCurrentHours()
        {
            return this.shouldSerialize["current_hours"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCurrentRate()
        {
            return this.shouldSerialize["current_rate"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is EarningsTotal other &&
                (this.CanonicalDescription == null && other.CanonicalDescription == null ||
                 this.CanonicalDescription?.Equals(other.CanonicalDescription) == true) &&
                (this.Description == null && other.Description == null ||
                 this.Description?.Equals(other.Description) == true) &&
                (this.CurrentPay == null && other.CurrentPay == null ||
                 this.CurrentPay?.Equals(other.CurrentPay) == true) &&
                (this.YtdPay == null && other.YtdPay == null ||
                 this.YtdPay?.Equals(other.YtdPay) == true) &&
                (this.CurrentHours == null && other.CurrentHours == null ||
                 this.CurrentHours?.Equals(other.CurrentHours) == true) &&
                (this.CurrentRate == null && other.CurrentRate == null ||
                 this.CurrentRate?.Equals(other.CurrentRate) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CanonicalDescription = {(this.CanonicalDescription == null ? "null" : this.CanonicalDescription.ToString())}");
            toStringOutput.Add($"Description = {this.Description ?? "null"}");
            toStringOutput.Add($"CurrentPay = {(this.CurrentPay == null ? "null" : this.CurrentPay.ToString())}");
            toStringOutput.Add($"YtdPay = {(this.YtdPay == null ? "null" : this.YtdPay.ToString())}");
            toStringOutput.Add($"CurrentHours = {this.CurrentHours ?? "null"}");
            toStringOutput.Add($"CurrentRate = {this.CurrentRate ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}