// <copyright file="HistoricalBalance.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// HistoricalBalance.
    /// </summary>
    public class HistoricalBalance
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricalBalance"/> class.
        /// </summary>
        public HistoricalBalance()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricalBalance"/> class.
        /// </summary>
        /// <param name="date">date.</param>
        /// <param name="current">current.</param>
        /// <param name="isoCurrencyCode">iso_currency_code.</param>
        /// <param name="unofficialCurrencyCode">unofficial_currency_code.</param>
        public HistoricalBalance(
            DateTime date,
            double current,
            string isoCurrencyCode = null,
            string unofficialCurrencyCode = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Date = date;
            this.Current = current;
            this.IsoCurrencyCode = isoCurrencyCode;
            this.UnofficialCurrencyCode = unofficialCurrencyCode;
        }

        /// <summary>
        /// The date of the calculated historical balance, in an [ISO 8601](https://wikipedia.org/wiki/ISO_8601) format (YYYY-MM-DD)
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("date")]
        public DateTime Date { get; set; }

        /// <summary>
        /// The total amount of funds in the account, calculated from the `current` balance in the `balance` object by subtracting inflows and adding back outflows according to the posted date of each transaction.
        /// If the account has any pending transactions, historical balance amounts on or after the date of the earliest pending transaction may differ if retrieved in subsequent Asset Reports as a result of those pending transactions posting.
        /// </summary>
        [JsonProperty("current")]
        public double Current { get; set; }

        /// <summary>
        /// The ISO-4217 currency code of the balance. Always `null` if `unofficial_currency_code` is non-`null`.
        /// </summary>
        [JsonProperty("iso_currency_code", NullValueHandling = NullValueHandling.Include)]
        public string IsoCurrencyCode { get; set; }

        /// <summary>
        /// The unofficial currency code associated with the balance. Always `null` if `iso_currency_code` is non-`null`.
        /// See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
        /// </summary>
        [JsonProperty("unofficial_currency_code", NullValueHandling = NullValueHandling.Include)]
        public string UnofficialCurrencyCode { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"HistoricalBalance : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is HistoricalBalance other &&
                (this.Date.Equals(other.Date)) &&
                (this.Current.Equals(other.Current)) &&
                (this.IsoCurrencyCode == null && other.IsoCurrencyCode == null ||
                 this.IsoCurrencyCode?.Equals(other.IsoCurrencyCode) == true) &&
                (this.UnofficialCurrencyCode == null && other.UnofficialCurrencyCode == null ||
                 this.UnofficialCurrencyCode?.Equals(other.UnofficialCurrencyCode) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Date = {this.Date}");
            toStringOutput.Add($"Current = {this.Current}");
            toStringOutput.Add($"IsoCurrencyCode = {this.IsoCurrencyCode ?? "null"}");
            toStringOutput.Add($"UnofficialCurrencyCode = {this.UnofficialCurrencyCode ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}