// <copyright file="HistoricalUpdateWebhook.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// HistoricalUpdateWebhook.
    /// </summary>
    public class HistoricalUpdateWebhook
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricalUpdateWebhook"/> class.
        /// </summary>
        public HistoricalUpdateWebhook()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricalUpdateWebhook"/> class.
        /// </summary>
        /// <param name="webhookType">webhook_type.</param>
        /// <param name="webhookCode">webhook_code.</param>
        /// <param name="newTransactions">new_transactions.</param>
        /// <param name="itemId">item_id.</param>
        /// <param name="error">error.</param>
        public HistoricalUpdateWebhook(
            string webhookType,
            string webhookCode,
            double newTransactions,
            string itemId,
            Models.Error error = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.WebhookType = webhookType;
            this.WebhookCode = webhookCode;
            this.Error = error;
            this.NewTransactions = newTransactions;
            this.ItemId = itemId;
        }

        /// <summary>
        /// `TRANSACTIONS`
        /// </summary>
        [JsonProperty("webhook_type")]
        public string WebhookType { get; set; }

        /// <summary>
        /// `HISTORICAL_UPDATE`
        /// </summary>
        [JsonProperty("webhook_code")]
        public string WebhookCode { get; set; }

        /// <summary>
        /// We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues.  Error fields will be `null` if no error has occurred.
        /// </summary>
        [JsonProperty("error", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Error Error { get; set; }

        /// <summary>
        /// The number of new, unfetched transactions available
        /// </summary>
        [JsonProperty("new_transactions")]
        public double NewTransactions { get; set; }

        /// <summary>
        /// The `item_id` of the Item associated with this webhook, warning, or error
        /// </summary>
        [JsonProperty("item_id")]
        public string ItemId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"HistoricalUpdateWebhook : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is HistoricalUpdateWebhook other &&
                (this.WebhookType == null && other.WebhookType == null ||
                 this.WebhookType?.Equals(other.WebhookType) == true) &&
                (this.WebhookCode == null && other.WebhookCode == null ||
                 this.WebhookCode?.Equals(other.WebhookCode) == true) &&
                (this.Error == null && other.Error == null ||
                 this.Error?.Equals(other.Error) == true) &&
                (this.NewTransactions.Equals(other.NewTransactions)) &&
                (this.ItemId == null && other.ItemId == null ||
                 this.ItemId?.Equals(other.ItemId) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"WebhookType = {this.WebhookType ?? "null"}");
            toStringOutput.Add($"WebhookCode = {this.WebhookCode ?? "null"}");
            toStringOutput.Add($"Error = {(this.Error == null ? "null" : this.Error.ToString())}");
            toStringOutput.Add($"NewTransactions = {this.NewTransactions}");
            toStringOutput.Add($"ItemId = {this.ItemId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}