// <copyright file="Holding.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// Holding.
    /// </summary>
    public class Holding
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Holding"/> class.
        /// </summary>
        public Holding()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Holding"/> class.
        /// </summary>
        /// <param name="accountId">account_id.</param>
        /// <param name="securityId">security_id.</param>
        /// <param name="institutionPrice">institution_price.</param>
        /// <param name="institutionValue">institution_value.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="institutionPriceAsOf">institution_price_as_of.</param>
        /// <param name="costBasis">cost_basis.</param>
        /// <param name="isoCurrencyCode">iso_currency_code.</param>
        /// <param name="unofficialCurrencyCode">unofficial_currency_code.</param>
        public Holding(
            string accountId,
            string securityId,
            double institutionPrice,
            double institutionValue,
            double quantity,
            DateTime? institutionPriceAsOf = null,
            double? costBasis = null,
            string isoCurrencyCode = null,
            string unofficialCurrencyCode = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.AccountId = accountId;
            this.SecurityId = securityId;
            this.InstitutionPrice = institutionPrice;
            this.InstitutionPriceAsOf = institutionPriceAsOf;
            this.InstitutionValue = institutionValue;
            this.CostBasis = costBasis;
            this.Quantity = quantity;
            this.IsoCurrencyCode = isoCurrencyCode;
            this.UnofficialCurrencyCode = unofficialCurrencyCode;
        }

        /// <summary>
        /// The Plaid `account_id` associated with the holding.
        /// </summary>
        [JsonProperty("account_id")]
        public string AccountId { get; set; }

        /// <summary>
        /// The Plaid `security_id` associated with the holding.
        /// </summary>
        [JsonProperty("security_id")]
        public string SecurityId { get; set; }

        /// <summary>
        /// The last price given by the institution for this security.
        /// </summary>
        [JsonProperty("institution_price")]
        public double InstitutionPrice { get; set; }

        /// <summary>
        /// The date at which `institution_price` was current.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("institution_price_as_of", NullValueHandling = NullValueHandling.Include)]
        public DateTime? InstitutionPriceAsOf { get; set; }

        /// <summary>
        /// The value of the holding, as reported by the institution.
        /// </summary>
        [JsonProperty("institution_value")]
        public double InstitutionValue { get; set; }

        /// <summary>
        /// The cost basis of the holding.
        /// </summary>
        [JsonProperty("cost_basis", NullValueHandling = NullValueHandling.Include)]
        public double? CostBasis { get; set; }

        /// <summary>
        /// The total quantity of the asset held, as reported by the financial institution. If the security is an option, `quantity` will reflect the total number of options (typically the number of contracts multiplied by 100), not the number of contracts.
        /// </summary>
        [JsonProperty("quantity")]
        public double Quantity { get; set; }

        /// <summary>
        /// The ISO-4217 currency code of the holding. Always `null` if `unofficial_currency_code` is non-`null`.
        /// </summary>
        [JsonProperty("iso_currency_code", NullValueHandling = NullValueHandling.Include)]
        public string IsoCurrencyCode { get; set; }

        /// <summary>
        /// The unofficial currency code associated with the holding. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.
        /// See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
        /// </summary>
        [JsonProperty("unofficial_currency_code", NullValueHandling = NullValueHandling.Include)]
        public string UnofficialCurrencyCode { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Holding : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Holding other &&
                (this.AccountId == null && other.AccountId == null ||
                 this.AccountId?.Equals(other.AccountId) == true) &&
                (this.SecurityId == null && other.SecurityId == null ||
                 this.SecurityId?.Equals(other.SecurityId) == true) &&
                (this.InstitutionPrice.Equals(other.InstitutionPrice)) &&
                (this.InstitutionPriceAsOf == null && other.InstitutionPriceAsOf == null ||
                 this.InstitutionPriceAsOf?.Equals(other.InstitutionPriceAsOf) == true) &&
                (this.InstitutionValue.Equals(other.InstitutionValue)) &&
                (this.CostBasis == null && other.CostBasis == null ||
                 this.CostBasis?.Equals(other.CostBasis) == true) &&
                (this.Quantity.Equals(other.Quantity)) &&
                (this.IsoCurrencyCode == null && other.IsoCurrencyCode == null ||
                 this.IsoCurrencyCode?.Equals(other.IsoCurrencyCode) == true) &&
                (this.UnofficialCurrencyCode == null && other.UnofficialCurrencyCode == null ||
                 this.UnofficialCurrencyCode?.Equals(other.UnofficialCurrencyCode) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountId = {this.AccountId ?? "null"}");
            toStringOutput.Add($"SecurityId = {this.SecurityId ?? "null"}");
            toStringOutput.Add($"InstitutionPrice = {this.InstitutionPrice}");
            toStringOutput.Add($"InstitutionPriceAsOf = {(this.InstitutionPriceAsOf == null ? "null" : this.InstitutionPriceAsOf.ToString())}");
            toStringOutput.Add($"InstitutionValue = {this.InstitutionValue}");
            toStringOutput.Add($"CostBasis = {(this.CostBasis == null ? "null" : this.CostBasis.ToString())}");
            toStringOutput.Add($"Quantity = {this.Quantity}");
            toStringOutput.Add($"IsoCurrencyCode = {this.IsoCurrencyCode ?? "null"}");
            toStringOutput.Add($"UnofficialCurrencyCode = {this.UnofficialCurrencyCode ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}