// <copyright file="IncomeSummary.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// IncomeSummary.
    /// </summary>
    public class IncomeSummary
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IncomeSummary"/> class.
        /// </summary>
        public IncomeSummary()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IncomeSummary"/> class.
        /// </summary>
        /// <param name="employerName">employer_name.</param>
        /// <param name="employeeName">employee_name.</param>
        /// <param name="ytdGrossIncome">ytd_gross_income.</param>
        /// <param name="ytdNetIncome">ytd_net_income.</param>
        /// <param name="payFrequency">pay_frequency.</param>
        /// <param name="projectedWage">projected_wage.</param>
        /// <param name="verifiedTransaction">verified_transaction.</param>
        public IncomeSummary(
            Models.EmployerIncomeSummaryFieldString employerName,
            Models.EmployeeIncomeSummaryFieldString employeeName,
            Models.YtdGrossIncomeSummaryFieldNumber ytdGrossIncome,
            Models.YtdNetIncomeSummaryFieldNumber ytdNetIncome,
            Models.PayFrequency payFrequency,
            Models.ProjectedIncomeSummaryFieldNumber projectedWage,
            Models.TransactionData verifiedTransaction)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.EmployerName = employerName;
            this.EmployeeName = employeeName;
            this.YtdGrossIncome = ytdGrossIncome;
            this.YtdNetIncome = ytdNetIncome;
            this.PayFrequency = payFrequency;
            this.ProjectedWage = projectedWage;
            this.VerifiedTransaction = verifiedTransaction;
        }

        /// <summary>
        /// Gets or sets EmployerName.
        /// </summary>
        [JsonProperty("employer_name")]
        public Models.EmployerIncomeSummaryFieldString EmployerName { get; set; }

        /// <summary>
        /// Gets or sets EmployeeName.
        /// </summary>
        [JsonProperty("employee_name")]
        public Models.EmployeeIncomeSummaryFieldString EmployeeName { get; set; }

        /// <summary>
        /// Gets or sets YtdGrossIncome.
        /// </summary>
        [JsonProperty("ytd_gross_income")]
        public Models.YtdGrossIncomeSummaryFieldNumber YtdGrossIncome { get; set; }

        /// <summary>
        /// Gets or sets YtdNetIncome.
        /// </summary>
        [JsonProperty("ytd_net_income")]
        public Models.YtdNetIncomeSummaryFieldNumber YtdNetIncome { get; set; }

        /// <summary>
        /// Gets or sets PayFrequency.
        /// </summary>
        [JsonProperty("pay_frequency")]
        public Models.PayFrequency PayFrequency { get; set; }

        /// <summary>
        /// Gets or sets ProjectedWage.
        /// </summary>
        [JsonProperty("projected_wage")]
        public Models.ProjectedIncomeSummaryFieldNumber ProjectedWage { get; set; }

        /// <summary>
        /// Information about the matched direct deposit transaction used to verify a user's payroll information.
        /// </summary>
        [JsonProperty("verified_transaction")]
        public Models.TransactionData VerifiedTransaction { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"IncomeSummary : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is IncomeSummary other &&
                (this.EmployerName == null && other.EmployerName == null ||
                 this.EmployerName?.Equals(other.EmployerName) == true) &&
                (this.EmployeeName == null && other.EmployeeName == null ||
                 this.EmployeeName?.Equals(other.EmployeeName) == true) &&
                (this.YtdGrossIncome == null && other.YtdGrossIncome == null ||
                 this.YtdGrossIncome?.Equals(other.YtdGrossIncome) == true) &&
                (this.YtdNetIncome == null && other.YtdNetIncome == null ||
                 this.YtdNetIncome?.Equals(other.YtdNetIncome) == true) &&
                (this.PayFrequency == null && other.PayFrequency == null ||
                 this.PayFrequency?.Equals(other.PayFrequency) == true) &&
                (this.ProjectedWage == null && other.ProjectedWage == null ||
                 this.ProjectedWage?.Equals(other.ProjectedWage) == true) &&
                (this.VerifiedTransaction == null && other.VerifiedTransaction == null ||
                 this.VerifiedTransaction?.Equals(other.VerifiedTransaction) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"EmployerName = {(this.EmployerName == null ? "null" : this.EmployerName.ToString())}");
            toStringOutput.Add($"EmployeeName = {(this.EmployeeName == null ? "null" : this.EmployeeName.ToString())}");
            toStringOutput.Add($"YtdGrossIncome = {(this.YtdGrossIncome == null ? "null" : this.YtdGrossIncome.ToString())}");
            toStringOutput.Add($"YtdNetIncome = {(this.YtdNetIncome == null ? "null" : this.YtdNetIncome.ToString())}");
            toStringOutput.Add($"PayFrequency = {(this.PayFrequency == null ? "null" : this.PayFrequency.ToString())}");
            toStringOutput.Add($"ProjectedWage = {(this.ProjectedWage == null ? "null" : this.ProjectedWage.ToString())}");
            toStringOutput.Add($"VerifiedTransaction = {(this.VerifiedTransaction == null ? "null" : this.VerifiedTransaction.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}