// <copyright file="IncomeVerificationRefreshRequest.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// IncomeVerificationRefreshRequest.
    /// </summary>
    public class IncomeVerificationRefreshRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string incomeVerificationId;
        private string accessToken;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "income_verification_id", false },
            { "access_token", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="IncomeVerificationRefreshRequest"/> class.
        /// </summary>
        public IncomeVerificationRefreshRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IncomeVerificationRefreshRequest"/> class.
        /// </summary>
        /// <param name="clientId">client_id.</param>
        /// <param name="secret">secret.</param>
        /// <param name="incomeVerificationId">income_verification_id.</param>
        /// <param name="accessToken">access_token.</param>
        public IncomeVerificationRefreshRequest(
            string clientId = null,
            string secret = null,
            string incomeVerificationId = null,
            string accessToken = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ClientId = clientId;
            this.Secret = secret;

            if (incomeVerificationId != null)
            {
                this.IncomeVerificationId = incomeVerificationId;
            }

            if (accessToken != null)
            {
                this.AccessToken = accessToken;
            }
        }

        /// <summary>
        /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
        /// </summary>
        [JsonProperty("client_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ClientId { get; set; }

        /// <summary>
        /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
        /// </summary>
        [JsonProperty("secret", NullValueHandling = NullValueHandling.Ignore)]
        public string Secret { get; set; }

        /// <summary>
        /// The ID of the verification.
        /// </summary>
        [JsonProperty("income_verification_id")]
        public string IncomeVerificationId
        {
            get
            {
                return this.incomeVerificationId;
            }

            set
            {
                this.shouldSerialize["income_verification_id"] = true;
                this.incomeVerificationId = value;
            }
        }

        /// <summary>
        /// The access token associated with the Item data is being requested for.
        /// </summary>
        [JsonProperty("access_token")]
        public string AccessToken
        {
            get
            {
                return this.accessToken;
            }

            set
            {
                this.shouldSerialize["access_token"] = true;
                this.accessToken = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"IncomeVerificationRefreshRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetIncomeVerificationId()
        {
            this.shouldSerialize["income_verification_id"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccessToken()
        {
            this.shouldSerialize["access_token"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeIncomeVerificationId()
        {
            return this.shouldSerialize["income_verification_id"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccessToken()
        {
            return this.shouldSerialize["access_token"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is IncomeVerificationRefreshRequest other &&
                (this.ClientId == null && other.ClientId == null ||
                 this.ClientId?.Equals(other.ClientId) == true) &&
                (this.Secret == null && other.Secret == null ||
                 this.Secret?.Equals(other.Secret) == true) &&
                (this.IncomeVerificationId == null && other.IncomeVerificationId == null ||
                 this.IncomeVerificationId?.Equals(other.IncomeVerificationId) == true) &&
                (this.AccessToken == null && other.AccessToken == null ||
                 this.AccessToken?.Equals(other.AccessToken) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ClientId = {this.ClientId ?? "null"}");
            toStringOutput.Add($"Secret = {this.Secret ?? "null"}");
            toStringOutput.Add($"IncomeVerificationId = {this.IncomeVerificationId ?? "null"}");
            toStringOutput.Add($"AccessToken = {this.AccessToken ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}