// <copyright file="InstitutionsSearchRequest.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// InstitutionsSearchRequest.
    /// </summary>
    public class InstitutionsSearchRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstitutionsSearchRequest"/> class.
        /// </summary>
        public InstitutionsSearchRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstitutionsSearchRequest"/> class.
        /// </summary>
        /// <param name="query">query.</param>
        /// <param name="products">products.</param>
        /// <param name="countryCodes">country_codes.</param>
        /// <param name="clientId">client_id.</param>
        /// <param name="secret">secret.</param>
        /// <param name="options">options.</param>
        public InstitutionsSearchRequest(
            string query,
            List<Models.Products> products,
            List<Models.CountryCode> countryCodes,
            string clientId = null,
            string secret = null,
            Models.InstitutionsSearchRequestOptions options = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ClientId = clientId;
            this.Secret = secret;
            this.Query = query;
            this.Products = products;
            this.CountryCodes = countryCodes;
            this.Options = options;
        }

        /// <summary>
        /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
        /// </summary>
        [JsonProperty("client_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ClientId { get; set; }

        /// <summary>
        /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
        /// </summary>
        [JsonProperty("secret", NullValueHandling = NullValueHandling.Ignore)]
        public string Secret { get; set; }

        /// <summary>
        /// The search query. Institutions with names matching the query are returned
        /// </summary>
        [JsonProperty("query")]
        public string Query { get; set; }

        /// <summary>
        /// Filter the Institutions based on whether they support all products listed in `products`. Provide `null` to get institutions regardless of supported products. Note that when `auth` is specified as a product, if you are enabled for Instant Match or Automated Micro-deposits, institutions that support those products will be returned even if `auth` is not present in their product array.
        /// </summary>
        [JsonProperty("products")]
        public List<Models.Products> Products { get; set; }

        /// <summary>
        /// Specify an array of Plaid-supported country codes this institution supports, using the ISO-3166-1 alpha-2 country code standard.
        /// </summary>
        [JsonProperty("country_codes")]
        public List<Models.CountryCode> CountryCodes { get; set; }

        /// <summary>
        /// An optional object to filter `/institutions/search` results.
        /// </summary>
        [JsonProperty("options", NullValueHandling = NullValueHandling.Ignore)]
        public Models.InstitutionsSearchRequestOptions Options { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InstitutionsSearchRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InstitutionsSearchRequest other &&
                (this.ClientId == null && other.ClientId == null ||
                 this.ClientId?.Equals(other.ClientId) == true) &&
                (this.Secret == null && other.Secret == null ||
                 this.Secret?.Equals(other.Secret) == true) &&
                (this.Query == null && other.Query == null ||
                 this.Query?.Equals(other.Query) == true) &&
                (this.Products == null && other.Products == null ||
                 this.Products?.Equals(other.Products) == true) &&
                (this.CountryCodes == null && other.CountryCodes == null ||
                 this.CountryCodes?.Equals(other.CountryCodes) == true) &&
                (this.Options == null && other.Options == null ||
                 this.Options?.Equals(other.Options) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ClientId = {this.ClientId ?? "null"}");
            toStringOutput.Add($"Secret = {this.Secret ?? "null"}");
            toStringOutput.Add($"Query = {this.Query ?? "null"}");
            toStringOutput.Add($"Products = {(this.Products == null ? "null" : $"[{string.Join(", ", this.Products)} ]")}");
            toStringOutput.Add($"CountryCodes = {(this.CountryCodes == null ? "null" : $"[{string.Join(", ", this.CountryCodes)} ]")}");
            toStringOutput.Add($"Options = {(this.Options == null ? "null" : this.Options.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}