// <copyright file="InvestmentTransaction.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// InvestmentTransaction.
    /// </summary>
    public class InvestmentTransaction
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string cancelTransactionId;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "cancel_transaction_id", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="InvestmentTransaction"/> class.
        /// </summary>
        public InvestmentTransaction()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InvestmentTransaction"/> class.
        /// </summary>
        /// <param name="investmentTransactionId">investment_transaction_id.</param>
        /// <param name="accountId">account_id.</param>
        /// <param name="date">date.</param>
        /// <param name="name">name.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="amount">amount.</param>
        /// <param name="price">price.</param>
        /// <param name="type">type.</param>
        /// <param name="subtype">subtype.</param>
        /// <param name="cancelTransactionId">cancel_transaction_id.</param>
        /// <param name="securityId">security_id.</param>
        /// <param name="fees">fees.</param>
        /// <param name="isoCurrencyCode">iso_currency_code.</param>
        /// <param name="unofficialCurrencyCode">unofficial_currency_code.</param>
        public InvestmentTransaction(
            string investmentTransactionId,
            string accountId,
            DateTime date,
            string name,
            double quantity,
            double amount,
            double price,
            Models.Type4 type,
            Models.Subtype subtype,
            string cancelTransactionId = null,
            string securityId = null,
            double? fees = null,
            string isoCurrencyCode = null,
            string unofficialCurrencyCode = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.InvestmentTransactionId = investmentTransactionId;

            if (cancelTransactionId != null)
            {
                this.CancelTransactionId = cancelTransactionId;
            }
            this.AccountId = accountId;
            this.SecurityId = securityId;
            this.Date = date;
            this.Name = name;
            this.Quantity = quantity;
            this.Amount = amount;
            this.Price = price;
            this.Fees = fees;
            this.Type = type;
            this.Subtype = subtype;
            this.IsoCurrencyCode = isoCurrencyCode;
            this.UnofficialCurrencyCode = unofficialCurrencyCode;
        }

        /// <summary>
        /// The ID of the Investment transaction, unique across all Plaid transactions. Like all Plaid identifiers, the `investment_transaction_id` is case sensitive.
        /// </summary>
        [JsonProperty("investment_transaction_id")]
        public string InvestmentTransactionId { get; set; }

        /// <summary>
        /// A legacy field formerly used internally by Plaid to identify certain canceled transactions.
        /// </summary>
        [JsonProperty("cancel_transaction_id")]
        public string CancelTransactionId
        {
            get
            {
                return this.cancelTransactionId;
            }

            set
            {
                this.shouldSerialize["cancel_transaction_id"] = true;
                this.cancelTransactionId = value;
            }
        }

        /// <summary>
        /// The `account_id` of the account against which this transaction posted.
        /// </summary>
        [JsonProperty("account_id")]
        public string AccountId { get; set; }

        /// <summary>
        /// The `security_id` to which this transaction is related.
        /// </summary>
        [JsonProperty("security_id", NullValueHandling = NullValueHandling.Include)]
        public string SecurityId { get; set; }

        /// <summary>
        /// The [ISO 8601](https://wikipedia.org/wiki/ISO_8601) posting date for the transaction, or transacted date for pending transactions.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("date")]
        public DateTime Date { get; set; }

        /// <summary>
        /// The institution’s description of the transaction.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// The number of units of the security involved in this transaction.
        /// </summary>
        [JsonProperty("quantity")]
        public double Quantity { get; set; }

        /// <summary>
        /// The complete value of the transaction. Positive values when cash is debited, e.g. purchases of stock; negative values when cash is credited, e.g. sales of stock. Treatment remains the same for cash-only movements unassociated with securities.
        /// </summary>
        [JsonProperty("amount")]
        public double Amount { get; set; }

        /// <summary>
        /// The price of the security at which this transaction occurred.
        /// </summary>
        [JsonProperty("price")]
        public double Price { get; set; }

        /// <summary>
        /// The combined value of all fees applied to this transaction
        /// </summary>
        [JsonProperty("fees", NullValueHandling = NullValueHandling.Include)]
        public double? Fees { get; set; }

        /// <summary>
        /// Value is one of the following:
        /// `buy`: Buying an investment
        /// `sell`: Selling an investment
        /// `cancel`: A cancellation of a pending transaction
        /// `cash`: Activity that modifies a cash position
        /// `fee`: A fee on the account
        /// `transfer`: Activity which modifies a position, but not through buy/sell activity e.g. options exercise, portfolio transfer
        /// For descriptions of possible transaction types and subtypes, see the [Investment transaction types schema](https://plaid.com/docs/api/accounts/#investment-transaction-types-schema).
        /// </summary>
        [JsonProperty("type")]
        public Models.Type4 Type { get; set; }

        /// <summary>
        /// For descriptions of possible transaction types and subtypes, see the [Investment transaction types schema](https://plaid.com/docs/api/accounts/#investment-transaction-types-schema).
        /// </summary>
        [JsonProperty("subtype")]
        public Models.Subtype Subtype { get; set; }

        /// <summary>
        /// The ISO-4217 currency code of the transaction. Always `null` if `unofficial_currency_code` is non-`null`.
        /// </summary>
        [JsonProperty("iso_currency_code", NullValueHandling = NullValueHandling.Include)]
        public string IsoCurrencyCode { get; set; }

        /// <summary>
        /// The unofficial currency code associated with the holding. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.
        /// See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
        /// </summary>
        [JsonProperty("unofficial_currency_code", NullValueHandling = NullValueHandling.Include)]
        public string UnofficialCurrencyCode { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InvestmentTransaction : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCancelTransactionId()
        {
            this.shouldSerialize["cancel_transaction_id"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCancelTransactionId()
        {
            return this.shouldSerialize["cancel_transaction_id"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InvestmentTransaction other &&
                (this.InvestmentTransactionId == null && other.InvestmentTransactionId == null ||
                 this.InvestmentTransactionId?.Equals(other.InvestmentTransactionId) == true) &&
                (this.CancelTransactionId == null && other.CancelTransactionId == null ||
                 this.CancelTransactionId?.Equals(other.CancelTransactionId) == true) &&
                (this.AccountId == null && other.AccountId == null ||
                 this.AccountId?.Equals(other.AccountId) == true) &&
                (this.SecurityId == null && other.SecurityId == null ||
                 this.SecurityId?.Equals(other.SecurityId) == true) &&
                (this.Date.Equals(other.Date)) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.Quantity.Equals(other.Quantity)) &&
                (this.Amount.Equals(other.Amount)) &&
                (this.Price.Equals(other.Price)) &&
                (this.Fees == null && other.Fees == null ||
                 this.Fees?.Equals(other.Fees) == true) &&
                (this.Type.Equals(other.Type)) &&
                (this.Subtype.Equals(other.Subtype)) &&
                (this.IsoCurrencyCode == null && other.IsoCurrencyCode == null ||
                 this.IsoCurrencyCode?.Equals(other.IsoCurrencyCode) == true) &&
                (this.UnofficialCurrencyCode == null && other.UnofficialCurrencyCode == null ||
                 this.UnofficialCurrencyCode?.Equals(other.UnofficialCurrencyCode) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"InvestmentTransactionId = {this.InvestmentTransactionId ?? "null"}");
            toStringOutput.Add($"CancelTransactionId = {this.CancelTransactionId ?? "null"}");
            toStringOutput.Add($"AccountId = {this.AccountId ?? "null"}");
            toStringOutput.Add($"SecurityId = {this.SecurityId ?? "null"}");
            toStringOutput.Add($"Date = {this.Date}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Quantity = {this.Quantity}");
            toStringOutput.Add($"Amount = {this.Amount}");
            toStringOutput.Add($"Price = {this.Price}");
            toStringOutput.Add($"Fees = {(this.Fees == null ? "null" : this.Fees.ToString())}");
            toStringOutput.Add($"Type = {this.Type}");
            toStringOutput.Add($"Subtype = {this.Subtype}");
            toStringOutput.Add($"IsoCurrencyCode = {this.IsoCurrencyCode ?? "null"}");
            toStringOutput.Add($"UnofficialCurrencyCode = {this.UnofficialCurrencyCode ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}