// <copyright file="InvestmentsHoldingsGetResponse.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// InvestmentsHoldingsGetResponse.
    /// </summary>
    public class InvestmentsHoldingsGetResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InvestmentsHoldingsGetResponse"/> class.
        /// </summary>
        public InvestmentsHoldingsGetResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InvestmentsHoldingsGetResponse"/> class.
        /// </summary>
        /// <param name="accounts">accounts.</param>
        /// <param name="holdings">holdings.</param>
        /// <param name="securities">securities.</param>
        /// <param name="item">item.</param>
        /// <param name="requestId">request_id.</param>
        public InvestmentsHoldingsGetResponse(
            List<Models.Account> accounts,
            List<Models.Holding> holdings,
            List<Models.Security> securities,
            Models.Item item,
            string requestId)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Accounts = accounts;
            this.Holdings = holdings;
            this.Securities = securities;
            this.Item = item;
            this.RequestId = requestId;
        }

        /// <summary>
        /// The accounts associated with the Item
        /// </summary>
        [JsonProperty("accounts")]
        public List<Models.Account> Accounts { get; set; }

        /// <summary>
        /// The holdings belonging to investment accounts associated with the Item. Details of the securities in the holdings are provided in the `securities` field.
        /// </summary>
        [JsonProperty("holdings")]
        public List<Models.Holding> Holdings { get; set; }

        /// <summary>
        /// Objects describing the securities held in the accounts associated with the Item.
        /// </summary>
        [JsonProperty("securities")]
        public List<Models.Security> Securities { get; set; }

        /// <summary>
        /// Metadata about the Item.
        /// </summary>
        [JsonProperty("item")]
        public Models.Item Item { get; set; }

        /// <summary>
        /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
        /// </summary>
        [JsonProperty("request_id")]
        public string RequestId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"InvestmentsHoldingsGetResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is InvestmentsHoldingsGetResponse other &&
                (this.Accounts == null && other.Accounts == null ||
                 this.Accounts?.Equals(other.Accounts) == true) &&
                (this.Holdings == null && other.Holdings == null ||
                 this.Holdings?.Equals(other.Holdings) == true) &&
                (this.Securities == null && other.Securities == null ||
                 this.Securities?.Equals(other.Securities) == true) &&
                (this.Item == null && other.Item == null ||
                 this.Item?.Equals(other.Item) == true) &&
                (this.RequestId == null && other.RequestId == null ||
                 this.RequestId?.Equals(other.RequestId) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Accounts = {(this.Accounts == null ? "null" : $"[{string.Join(", ", this.Accounts)} ]")}");
            toStringOutput.Add($"Holdings = {(this.Holdings == null ? "null" : $"[{string.Join(", ", this.Holdings)} ]")}");
            toStringOutput.Add($"Securities = {(this.Securities == null ? "null" : $"[{string.Join(", ", this.Securities)} ]")}");
            toStringOutput.Add($"Item = {(this.Item == null ? "null" : this.Item.ToString())}");
            toStringOutput.Add($"RequestId = {this.RequestId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}