// <copyright file="JwkPublicKey.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// JwkPublicKey.
    /// </summary>
    public class JwkPublicKey
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JwkPublicKey"/> class.
        /// </summary>
        public JwkPublicKey()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JwkPublicKey"/> class.
        /// </summary>
        /// <param name="alg">alg.</param>
        /// <param name="crv">crv.</param>
        /// <param name="kid">kid.</param>
        /// <param name="kty">kty.</param>
        /// <param name="use">use.</param>
        /// <param name="x">x.</param>
        /// <param name="y">y.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="expiredAt">expired_at.</param>
        public JwkPublicKey(
            string alg,
            string crv,
            string kid,
            string kty,
            string use,
            string x,
            string y,
            int createdAt,
            int? expiredAt = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Alg = alg;
            this.Crv = crv;
            this.Kid = kid;
            this.Kty = kty;
            this.Use = use;
            this.X = x;
            this.Y = y;
            this.CreatedAt = createdAt;
            this.ExpiredAt = expiredAt;
        }

        /// <summary>
        /// The alg member identifies the cryptographic algorithm family used with the key.
        /// </summary>
        [JsonProperty("alg")]
        public string Alg { get; set; }

        /// <summary>
        /// The crv member identifies the cryptographic curve used with the key.
        /// </summary>
        [JsonProperty("crv")]
        public string Crv { get; set; }

        /// <summary>
        /// The kid (Key ID) member can be used to match a specific key. This can be used, for instance, to choose among a set of keys within the JWK during key rollover.
        /// </summary>
        [JsonProperty("kid")]
        public string Kid { get; set; }

        /// <summary>
        /// The kty (key type) parameter identifies the cryptographic algorithm family used with the key, such as RSA or EC.
        /// </summary>
        [JsonProperty("kty")]
        public string Kty { get; set; }

        /// <summary>
        /// The use (public key use) parameter identifies the intended use of the public key.
        /// </summary>
        [JsonProperty("use")]
        public string Use { get; set; }

        /// <summary>
        /// The x member contains the x coordinate for the elliptic curve point.
        /// </summary>
        [JsonProperty("x")]
        public string X { get; set; }

        /// <summary>
        /// The y member contains the y coordinate for the elliptic curve point.
        /// </summary>
        [JsonProperty("y")]
        public string Y { get; set; }

        /// <summary>
        /// The timestamp when the key was created, in Unix time.
        /// </summary>
        [JsonProperty("created_at")]
        public int CreatedAt { get; set; }

        /// <summary>
        /// The timestamp when the key expired, in Unix time.
        /// </summary>
        [JsonProperty("expired_at", NullValueHandling = NullValueHandling.Include)]
        public int? ExpiredAt { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"JwkPublicKey : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is JwkPublicKey other &&
                (this.Alg == null && other.Alg == null ||
                 this.Alg?.Equals(other.Alg) == true) &&
                (this.Crv == null && other.Crv == null ||
                 this.Crv?.Equals(other.Crv) == true) &&
                (this.Kid == null && other.Kid == null ||
                 this.Kid?.Equals(other.Kid) == true) &&
                (this.Kty == null && other.Kty == null ||
                 this.Kty?.Equals(other.Kty) == true) &&
                (this.Use == null && other.Use == null ||
                 this.Use?.Equals(other.Use) == true) &&
                (this.X == null && other.X == null ||
                 this.X?.Equals(other.X) == true) &&
                (this.Y == null && other.Y == null ||
                 this.Y?.Equals(other.Y) == true) &&
                (this.CreatedAt.Equals(other.CreatedAt)) &&
                (this.ExpiredAt == null && other.ExpiredAt == null ||
                 this.ExpiredAt?.Equals(other.ExpiredAt) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Alg = {this.Alg ?? "null"}");
            toStringOutput.Add($"Crv = {this.Crv ?? "null"}");
            toStringOutput.Add($"Kid = {this.Kid ?? "null"}");
            toStringOutput.Add($"Kty = {this.Kty ?? "null"}");
            toStringOutput.Add($"Use = {this.Use ?? "null"}");
            toStringOutput.Add($"X = {this.X ?? "null"}");
            toStringOutput.Add($"Y = {this.Y ?? "null"}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"ExpiredAt = {(this.ExpiredAt == null ? "null" : this.ExpiredAt.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}