// <copyright file="LiabilityOverride.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// LiabilityOverride.
    /// </summary>
    public class LiabilityOverride
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LiabilityOverride"/> class.
        /// </summary>
        public LiabilityOverride()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LiabilityOverride"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="purchaseApr">purchase_apr.</param>
        /// <param name="cashApr">cash_apr.</param>
        /// <param name="balanceTransferApr">balance_transfer_apr.</param>
        /// <param name="specialApr">special_apr.</param>
        /// <param name="lastPaymentAmount">last_payment_amount.</param>
        /// <param name="minimumPaymentAmount">minimum_payment_amount.</param>
        /// <param name="isOverdue">is_overdue.</param>
        /// <param name="originationDate">origination_date.</param>
        /// <param name="principal">principal.</param>
        /// <param name="nominalApr">nominal_apr.</param>
        /// <param name="interestCapitalizationGracePeriodMonths">interest_capitalization_grace_period_months.</param>
        /// <param name="repaymentModel">repayment_model.</param>
        /// <param name="expectedPayoffDate">expected_payoff_date.</param>
        /// <param name="guarantor">guarantor.</param>
        /// <param name="isFederal">is_federal.</param>
        /// <param name="loanName">loan_name.</param>
        /// <param name="loanStatus">loan_status.</param>
        /// <param name="paymentReferenceNumber">payment_reference_number.</param>
        /// <param name="pslfStatus">pslf_status.</param>
        /// <param name="repaymentPlanDescription">repayment_plan_description.</param>
        /// <param name="repaymentPlanType">repayment_plan_type.</param>
        /// <param name="sequenceNumber">sequence_number.</param>
        /// <param name="servicerAddress">servicer_address.</param>
        public LiabilityOverride(
            string type,
            double purchaseApr,
            double cashApr,
            double balanceTransferApr,
            double specialApr,
            double lastPaymentAmount,
            double minimumPaymentAmount,
            bool isOverdue,
            DateTime originationDate,
            double principal,
            double nominalApr,
            double interestCapitalizationGracePeriodMonths,
            Models.StudentLoanRepaymentModel repaymentModel,
            DateTime expectedPayoffDate,
            string guarantor,
            bool isFederal,
            string loanName,
            Models.StudentLoanStatus loanStatus,
            string paymentReferenceNumber,
            Models.PslfStatus pslfStatus,
            string repaymentPlanDescription,
            string repaymentPlanType,
            string sequenceNumber,
            Models.Address servicerAddress)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Type = type;
            this.PurchaseApr = purchaseApr;
            this.CashApr = cashApr;
            this.BalanceTransferApr = balanceTransferApr;
            this.SpecialApr = specialApr;
            this.LastPaymentAmount = lastPaymentAmount;
            this.MinimumPaymentAmount = minimumPaymentAmount;
            this.IsOverdue = isOverdue;
            this.OriginationDate = originationDate;
            this.Principal = principal;
            this.NominalApr = nominalApr;
            this.InterestCapitalizationGracePeriodMonths = interestCapitalizationGracePeriodMonths;
            this.RepaymentModel = repaymentModel;
            this.ExpectedPayoffDate = expectedPayoffDate;
            this.Guarantor = guarantor;
            this.IsFederal = isFederal;
            this.LoanName = loanName;
            this.LoanStatus = loanStatus;
            this.PaymentReferenceNumber = paymentReferenceNumber;
            this.PslfStatus = pslfStatus;
            this.RepaymentPlanDescription = repaymentPlanDescription;
            this.RepaymentPlanType = repaymentPlanType;
            this.SequenceNumber = sequenceNumber;
            this.ServicerAddress = servicerAddress;
        }

        /// <summary>
        /// The type of the liability object, either `credit` or `student`. Mortgages are not currently supported in the custom Sandbox.
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }

        /// <summary>
        /// The purchase APR percentage value. For simplicity, this is the only interest rate used to calculate interest charges. Can only be set if `type` is `credit`.
        /// </summary>
        [JsonProperty("purchase_apr")]
        public double PurchaseApr { get; set; }

        /// <summary>
        /// The cash APR percentage value. Can only be set if `type` is `credit`.
        /// </summary>
        [JsonProperty("cash_apr")]
        public double CashApr { get; set; }

        /// <summary>
        /// The balance transfer APR percentage value. Can only be set if `type` is `credit`. Can only be set if `type` is `credit`.
        /// </summary>
        [JsonProperty("balance_transfer_apr")]
        public double BalanceTransferApr { get; set; }

        /// <summary>
        /// The special APR percentage value. Can only be set if `type` is `credit`.
        /// </summary>
        [JsonProperty("special_apr")]
        public double SpecialApr { get; set; }

        /// <summary>
        /// Override the `last_payment_amount` field. Can only be set if `type` is `credit`.
        /// </summary>
        [JsonProperty("last_payment_amount")]
        public double LastPaymentAmount { get; set; }

        /// <summary>
        /// Override the `minimum_payment_amount` field. Can only be set if `type` is `credit` or `student`.
        /// </summary>
        [JsonProperty("minimum_payment_amount")]
        public double MinimumPaymentAmount { get; set; }

        /// <summary>
        /// Override the `is_overdue` field
        /// </summary>
        [JsonProperty("is_overdue")]
        public bool IsOverdue { get; set; }

        /// <summary>
        /// The date on which the loan was initially lent, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format. Can only be set if `type` is `student`.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("origination_date")]
        public DateTime OriginationDate { get; set; }

        /// <summary>
        /// The original loan principal. Can only be set if `type` is `student`.
        /// </summary>
        [JsonProperty("principal")]
        public double Principal { get; set; }

        /// <summary>
        /// The interest rate on the loan as a percentage. Can only be set if `type` is `student`.
        /// </summary>
        [JsonProperty("nominal_apr")]
        public double NominalApr { get; set; }

        /// <summary>
        /// If set, interest capitalization begins at the given number of months after loan origination. By default interest is never capitalized. Can only be set if `type` is `student`.
        /// </summary>
        [JsonProperty("interest_capitalization_grace_period_months")]
        public double InterestCapitalizationGracePeriodMonths { get; set; }

        /// <summary>
        /// Student loan repayment information used to configure Sandbox test data for the Liabilities product
        /// </summary>
        [JsonProperty("repayment_model")]
        public Models.StudentLoanRepaymentModel RepaymentModel { get; set; }

        /// <summary>
        /// Override the `expected_payoff_date` field. Can only be set if `type` is `student`.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("expected_payoff_date")]
        public DateTime ExpectedPayoffDate { get; set; }

        /// <summary>
        /// Override the `guarantor` field. Can only be set if `type` is `student`.
        /// </summary>
        [JsonProperty("guarantor")]
        public string Guarantor { get; set; }

        /// <summary>
        /// Override the `is_federal` field. Can only be set if `type` is `student`.
        /// </summary>
        [JsonProperty("is_federal")]
        public bool IsFederal { get; set; }

        /// <summary>
        /// Override the `loan_name` field. Can only be set if `type` is `student`.
        /// </summary>
        [JsonProperty("loan_name")]
        public string LoanName { get; set; }

        /// <summary>
        /// An object representing the status of the student loan
        /// </summary>
        [JsonProperty("loan_status")]
        public Models.StudentLoanStatus LoanStatus { get; set; }

        /// <summary>
        /// Override the `payment_reference_number` field. Can only be set if `type` is `student`.
        /// </summary>
        [JsonProperty("payment_reference_number")]
        public string PaymentReferenceNumber { get; set; }

        /// <summary>
        /// Information about the student's eligibility in the Public Service Loan Forgiveness program. This is only returned if the institution is Fedloan (`ins_116527`).
        /// </summary>
        [JsonProperty("pslf_status")]
        public Models.PslfStatus PslfStatus { get; set; }

        /// <summary>
        /// Override the `repayment_plan.description` field. Can only be set if `type` is `student`.
        /// </summary>
        [JsonProperty("repayment_plan_description")]
        public string RepaymentPlanDescription { get; set; }

        /// <summary>
        /// Override the `repayment_plan.type` field. Can only be set if `type` is `student`. Possible values are: `"extended graduated"`, `"extended standard"`, `"graduated"`, `"income-contingent repayment"`, `"income-based repayment"`, `"interest only"`, `"other"`, `"pay as you earn"`, `"revised pay as you earn"`, or `"standard"`.
        /// </summary>
        [JsonProperty("repayment_plan_type")]
        public string RepaymentPlanType { get; set; }

        /// <summary>
        /// Override the `sequence_number` field. Can only be set if `type` is `student`.
        /// </summary>
        [JsonProperty("sequence_number")]
        public string SequenceNumber { get; set; }

        /// <summary>
        /// A physical mailing address.
        /// </summary>
        [JsonProperty("servicer_address")]
        public Models.Address ServicerAddress { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"LiabilityOverride : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is LiabilityOverride other &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true) &&
                (this.PurchaseApr.Equals(other.PurchaseApr)) &&
                (this.CashApr.Equals(other.CashApr)) &&
                (this.BalanceTransferApr.Equals(other.BalanceTransferApr)) &&
                (this.SpecialApr.Equals(other.SpecialApr)) &&
                (this.LastPaymentAmount.Equals(other.LastPaymentAmount)) &&
                (this.MinimumPaymentAmount.Equals(other.MinimumPaymentAmount)) &&
                (this.IsOverdue.Equals(other.IsOverdue)) &&
                (this.OriginationDate.Equals(other.OriginationDate)) &&
                (this.Principal.Equals(other.Principal)) &&
                (this.NominalApr.Equals(other.NominalApr)) &&
                (this.InterestCapitalizationGracePeriodMonths.Equals(other.InterestCapitalizationGracePeriodMonths)) &&
                (this.RepaymentModel == null && other.RepaymentModel == null ||
                 this.RepaymentModel?.Equals(other.RepaymentModel) == true) &&
                (this.ExpectedPayoffDate.Equals(other.ExpectedPayoffDate)) &&
                (this.Guarantor == null && other.Guarantor == null ||
                 this.Guarantor?.Equals(other.Guarantor) == true) &&
                (this.IsFederal.Equals(other.IsFederal)) &&
                (this.LoanName == null && other.LoanName == null ||
                 this.LoanName?.Equals(other.LoanName) == true) &&
                (this.LoanStatus == null && other.LoanStatus == null ||
                 this.LoanStatus?.Equals(other.LoanStatus) == true) &&
                (this.PaymentReferenceNumber == null && other.PaymentReferenceNumber == null ||
                 this.PaymentReferenceNumber?.Equals(other.PaymentReferenceNumber) == true) &&
                (this.PslfStatus == null && other.PslfStatus == null ||
                 this.PslfStatus?.Equals(other.PslfStatus) == true) &&
                (this.RepaymentPlanDescription == null && other.RepaymentPlanDescription == null ||
                 this.RepaymentPlanDescription?.Equals(other.RepaymentPlanDescription) == true) &&
                (this.RepaymentPlanType == null && other.RepaymentPlanType == null ||
                 this.RepaymentPlanType?.Equals(other.RepaymentPlanType) == true) &&
                (this.SequenceNumber == null && other.SequenceNumber == null ||
                 this.SequenceNumber?.Equals(other.SequenceNumber) == true) &&
                (this.ServicerAddress == null && other.ServicerAddress == null ||
                 this.ServicerAddress?.Equals(other.ServicerAddress) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"PurchaseApr = {this.PurchaseApr}");
            toStringOutput.Add($"CashApr = {this.CashApr}");
            toStringOutput.Add($"BalanceTransferApr = {this.BalanceTransferApr}");
            toStringOutput.Add($"SpecialApr = {this.SpecialApr}");
            toStringOutput.Add($"LastPaymentAmount = {this.LastPaymentAmount}");
            toStringOutput.Add($"MinimumPaymentAmount = {this.MinimumPaymentAmount}");
            toStringOutput.Add($"IsOverdue = {this.IsOverdue}");
            toStringOutput.Add($"OriginationDate = {this.OriginationDate}");
            toStringOutput.Add($"Principal = {this.Principal}");
            toStringOutput.Add($"NominalApr = {this.NominalApr}");
            toStringOutput.Add($"InterestCapitalizationGracePeriodMonths = {this.InterestCapitalizationGracePeriodMonths}");
            toStringOutput.Add($"RepaymentModel = {(this.RepaymentModel == null ? "null" : this.RepaymentModel.ToString())}");
            toStringOutput.Add($"ExpectedPayoffDate = {this.ExpectedPayoffDate}");
            toStringOutput.Add($"Guarantor = {this.Guarantor ?? "null"}");
            toStringOutput.Add($"IsFederal = {this.IsFederal}");
            toStringOutput.Add($"LoanName = {this.LoanName ?? "null"}");
            toStringOutput.Add($"LoanStatus = {(this.LoanStatus == null ? "null" : this.LoanStatus.ToString())}");
            toStringOutput.Add($"PaymentReferenceNumber = {this.PaymentReferenceNumber ?? "null"}");
            toStringOutput.Add($"PslfStatus = {(this.PslfStatus == null ? "null" : this.PslfStatus.ToString())}");
            toStringOutput.Add($"RepaymentPlanDescription = {this.RepaymentPlanDescription ?? "null"}");
            toStringOutput.Add($"RepaymentPlanType = {this.RepaymentPlanType ?? "null"}");
            toStringOutput.Add($"SequenceNumber = {this.SequenceNumber ?? "null"}");
            toStringOutput.Add($"ServicerAddress = {(this.ServicerAddress == null ? "null" : this.ServicerAddress.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}