// <copyright file="Mfa.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// Mfa.
    /// </summary>
    public class Mfa
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Mfa"/> class.
        /// </summary>
        public Mfa()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Mfa"/> class.
        /// </summary>
        /// <param name="type">type.</param>
        /// <param name="questionRounds">question_rounds.</param>
        /// <param name="questionsPerRound">questions_per_round.</param>
        /// <param name="selectionRounds">selection_rounds.</param>
        /// <param name="selectionsPerQuestion">selections_per_question.</param>
        public Mfa(
            string type,
            double questionRounds,
            double questionsPerRound,
            double selectionRounds,
            double selectionsPerQuestion)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Type = type;
            this.QuestionRounds = questionRounds;
            this.QuestionsPerRound = questionsPerRound;
            this.SelectionRounds = selectionRounds;
            this.SelectionsPerQuestion = selectionsPerQuestion;
        }

        /// <summary>
        /// <![CDATA[
        /// Possible values are `device`, `selections`, or `questions`.
        /// If value is `device`, the MFA answer is `1234`.
        /// If value is `selections`, the MFA answer is always the first option.
        /// If value is `questions`, the MFA answer is  `answer_<i>_<j>` for the j-th question in the i-th round, starting from 0. For example, the answer to the first question in the second round is `answer_1_0`.
        /// ]]>
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }

        /// <summary>
        /// Number of rounds of questions. Required if value of `type` is `questions`.
        /// </summary>
        [JsonProperty("question_rounds")]
        public double QuestionRounds { get; set; }

        /// <summary>
        /// Number of questions per round. Required if value of `type` is `questions`. If value of type is `selections`, default value is 2.
        /// </summary>
        [JsonProperty("questions_per_round")]
        public double QuestionsPerRound { get; set; }

        /// <summary>
        /// Number of rounds of selections, used if `type` is `selections`. Defaults to 1.
        /// </summary>
        [JsonProperty("selection_rounds")]
        public double SelectionRounds { get; set; }

        /// <summary>
        /// Number of available answers per question, used if `type` is `selection`. Defaults to 2.
        /// </summary>
        [JsonProperty("selections_per_question")]
        public double SelectionsPerQuestion { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Mfa : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Mfa other &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true) &&
                (this.QuestionRounds.Equals(other.QuestionRounds)) &&
                (this.QuestionsPerRound.Equals(other.QuestionsPerRound)) &&
                (this.SelectionRounds.Equals(other.SelectionRounds)) &&
                (this.SelectionsPerQuestion.Equals(other.SelectionsPerQuestion)) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"QuestionRounds = {this.QuestionRounds}");
            toStringOutput.Add($"QuestionsPerRound = {this.QuestionsPerRound}");
            toStringOutput.Add($"SelectionRounds = {this.SelectionRounds}");
            toStringOutput.Add($"SelectionsPerQuestion = {this.SelectionsPerQuestion}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}