// <copyright file="PaystubDetails.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// PaystubDetails.
    /// </summary>
    public class PaystubDetails
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private DateTime? payPeriodStartDate;
        private DateTime? payPeriodEndDate;
        private DateTime? payDate;
        private string paystubProvider;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "pay_period_start_date", false },
            { "pay_period_end_date", false },
            { "pay_date", false },
            { "paystub_provider", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="PaystubDetails"/> class.
        /// </summary>
        public PaystubDetails()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaystubDetails"/> class.
        /// </summary>
        /// <param name="payPeriodStartDate">pay_period_start_date.</param>
        /// <param name="payPeriodEndDate">pay_period_end_date.</param>
        /// <param name="payDate">pay_date.</param>
        /// <param name="paystubProvider">paystub_provider.</param>
        /// <param name="payFrequency">pay_frequency.</param>
        public PaystubDetails(
            DateTime? payPeriodStartDate = null,
            DateTime? payPeriodEndDate = null,
            DateTime? payDate = null,
            string paystubProvider = null,
            Models.PayFrequency1? payFrequency = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (payPeriodStartDate != null)
            {
                this.PayPeriodStartDate = payPeriodStartDate;
            }

            if (payPeriodEndDate != null)
            {
                this.PayPeriodEndDate = payPeriodEndDate;
            }

            if (payDate != null)
            {
                this.PayDate = payDate;
            }

            if (paystubProvider != null)
            {
                this.PaystubProvider = paystubProvider;
            }
            this.PayFrequency = payFrequency;
        }

        /// <summary>
        /// Beginning date of the pay period on the paystub in the 'YYYY-MM-DD' format.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("pay_period_start_date")]
        public DateTime? PayPeriodStartDate
        {
            get
            {
                return this.payPeriodStartDate;
            }

            set
            {
                this.shouldSerialize["pay_period_start_date"] = true;
                this.payPeriodStartDate = value;
            }
        }

        /// <summary>
        /// Ending date of the pay period on the paystub in the 'YYYY-MM-DD' format.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("pay_period_end_date")]
        public DateTime? PayPeriodEndDate
        {
            get
            {
                return this.payPeriodEndDate;
            }

            set
            {
                this.shouldSerialize["pay_period_end_date"] = true;
                this.payPeriodEndDate = value;
            }
        }

        /// <summary>
        /// Pay date on the paystub in the 'YYYY-MM-DD' format.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("pay_date")]
        public DateTime? PayDate
        {
            get
            {
                return this.payDate;
            }

            set
            {
                this.shouldSerialize["pay_date"] = true;
                this.payDate = value;
            }
        }

        /// <summary>
        /// The name of the payroll provider that generated the paystub, e.g. ADP
        /// </summary>
        [JsonProperty("paystub_provider")]
        public string PaystubProvider
        {
            get
            {
                return this.paystubProvider;
            }

            set
            {
                this.shouldSerialize["paystub_provider"] = true;
                this.paystubProvider = value;
            }
        }

        /// <summary>
        /// The frequency at which the employee is paid. Possible values: `MONTHLY`, `BI-WEEKLY`, `WEEKLY`, `SEMI-MONTHLY`.
        /// </summary>
        [JsonProperty("pay_frequency", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PayFrequency1? PayFrequency { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PaystubDetails : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPayPeriodStartDate()
        {
            this.shouldSerialize["pay_period_start_date"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPayPeriodEndDate()
        {
            this.shouldSerialize["pay_period_end_date"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPayDate()
        {
            this.shouldSerialize["pay_date"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPaystubProvider()
        {
            this.shouldSerialize["paystub_provider"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePayPeriodStartDate()
        {
            return this.shouldSerialize["pay_period_start_date"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePayPeriodEndDate()
        {
            return this.shouldSerialize["pay_period_end_date"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePayDate()
        {
            return this.shouldSerialize["pay_date"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePaystubProvider()
        {
            return this.shouldSerialize["paystub_provider"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is PaystubDetails other &&
                (this.PayPeriodStartDate == null && other.PayPeriodStartDate == null ||
                 this.PayPeriodStartDate?.Equals(other.PayPeriodStartDate) == true) &&
                (this.PayPeriodEndDate == null && other.PayPeriodEndDate == null ||
                 this.PayPeriodEndDate?.Equals(other.PayPeriodEndDate) == true) &&
                (this.PayDate == null && other.PayDate == null ||
                 this.PayDate?.Equals(other.PayDate) == true) &&
                (this.PaystubProvider == null && other.PaystubProvider == null ||
                 this.PaystubProvider?.Equals(other.PaystubProvider) == true) &&
                (this.PayFrequency == null && other.PayFrequency == null ||
                 this.PayFrequency?.Equals(other.PayFrequency) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PayPeriodStartDate = {(this.PayPeriodStartDate == null ? "null" : this.PayPeriodStartDate.ToString())}");
            toStringOutput.Add($"PayPeriodEndDate = {(this.PayPeriodEndDate == null ? "null" : this.PayPeriodEndDate.ToString())}");
            toStringOutput.Add($"PayDate = {(this.PayDate == null ? "null" : this.PayDate.ToString())}");
            toStringOutput.Add($"PaystubProvider = {this.PaystubProvider ?? "null"}");
            toStringOutput.Add($"PayFrequency = {(this.PayFrequency == null ? "null" : this.PayFrequency.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}