// <copyright file="SandboxIncomeFireWebhookRequest.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// SandboxIncomeFireWebhookRequest.
    /// </summary>
    public class SandboxIncomeFireWebhookRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SandboxIncomeFireWebhookRequest"/> class.
        /// </summary>
        public SandboxIncomeFireWebhookRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SandboxIncomeFireWebhookRequest"/> class.
        /// </summary>
        /// <param name="incomeVerificationId">income_verification_id.</param>
        /// <param name="webhook">webhook.</param>
        /// <param name="verificationStatus">verification_status.</param>
        /// <param name="clientId">client_id.</param>
        /// <param name="secret">secret.</param>
        public SandboxIncomeFireWebhookRequest(
            string incomeVerificationId,
            string webhook,
            Models.VerificationStatus3 verificationStatus,
            string clientId = null,
            string secret = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ClientId = clientId;
            this.Secret = secret;
            this.IncomeVerificationId = incomeVerificationId;
            this.Webhook = webhook;
            this.VerificationStatus = verificationStatus;
        }

        /// <summary>
        /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
        /// </summary>
        [JsonProperty("client_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ClientId { get; set; }

        /// <summary>
        /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
        /// </summary>
        [JsonProperty("secret", NullValueHandling = NullValueHandling.Ignore)]
        public string Secret { get; set; }

        /// <summary>
        /// The ID of the verification.
        /// </summary>
        [JsonProperty("income_verification_id")]
        public string IncomeVerificationId { get; set; }

        /// <summary>
        /// The URL to which the webhook should be sent.
        /// </summary>
        [JsonProperty("webhook")]
        public string Webhook { get; set; }

        /// <summary>
        /// `VERIFICATION_STATUS_PROCESSING_COMPLETE`: The income verification status processing has completed.
        /// `VERIFICATION_STATUS_DOCUMENT_REJECTED`: The documentation uploaded by the end user was recognized as a supported file format, but not recognized as a valid paystub.
        /// `VERIFICATION_STATUS_PROCESSING_FAILED`: A failure occurred when attempting to process the verification documentation.
        /// </summary>
        [JsonProperty("verification_status")]
        public Models.VerificationStatus3 VerificationStatus { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SandboxIncomeFireWebhookRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SandboxIncomeFireWebhookRequest other &&
                (this.ClientId == null && other.ClientId == null ||
                 this.ClientId?.Equals(other.ClientId) == true) &&
                (this.Secret == null && other.Secret == null ||
                 this.Secret?.Equals(other.Secret) == true) &&
                (this.IncomeVerificationId == null && other.IncomeVerificationId == null ||
                 this.IncomeVerificationId?.Equals(other.IncomeVerificationId) == true) &&
                (this.Webhook == null && other.Webhook == null ||
                 this.Webhook?.Equals(other.Webhook) == true) &&
                (this.VerificationStatus.Equals(other.VerificationStatus)) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ClientId = {this.ClientId ?? "null"}");
            toStringOutput.Add($"Secret = {this.Secret ?? "null"}");
            toStringOutput.Add($"IncomeVerificationId = {this.IncomeVerificationId ?? "null"}");
            toStringOutput.Add($"Webhook = {this.Webhook ?? "null"}");
            toStringOutput.Add($"VerificationStatus = {this.VerificationStatus}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}