// <copyright file="Security.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// Security.
    /// </summary>
    public class Security
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Security"/> class.
        /// </summary>
        public Security()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Security"/> class.
        /// </summary>
        /// <param name="securityId">security_id.</param>
        /// <param name="isin">isin.</param>
        /// <param name="cusip">cusip.</param>
        /// <param name="sedol">sedol.</param>
        /// <param name="institutionSecurityId">institution_security_id.</param>
        /// <param name="institutionId">institution_id.</param>
        /// <param name="proxySecurityId">proxy_security_id.</param>
        /// <param name="name">name.</param>
        /// <param name="tickerSymbol">ticker_symbol.</param>
        /// <param name="isCashEquivalent">is_cash_equivalent.</param>
        /// <param name="type">type.</param>
        /// <param name="closePrice">close_price.</param>
        /// <param name="closePriceAsOf">close_price_as_of.</param>
        /// <param name="isoCurrencyCode">iso_currency_code.</param>
        /// <param name="unofficialCurrencyCode">unofficial_currency_code.</param>
        public Security(
            string securityId,
            string isin = null,
            string cusip = null,
            string sedol = null,
            string institutionSecurityId = null,
            string institutionId = null,
            string proxySecurityId = null,
            string name = null,
            string tickerSymbol = null,
            bool? isCashEquivalent = null,
            string type = null,
            double? closePrice = null,
            DateTime? closePriceAsOf = null,
            string isoCurrencyCode = null,
            string unofficialCurrencyCode = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.SecurityId = securityId;
            this.Isin = isin;
            this.Cusip = cusip;
            this.Sedol = sedol;
            this.InstitutionSecurityId = institutionSecurityId;
            this.InstitutionId = institutionId;
            this.ProxySecurityId = proxySecurityId;
            this.Name = name;
            this.TickerSymbol = tickerSymbol;
            this.IsCashEquivalent = isCashEquivalent;
            this.Type = type;
            this.ClosePrice = closePrice;
            this.ClosePriceAsOf = closePriceAsOf;
            this.IsoCurrencyCode = isoCurrencyCode;
            this.UnofficialCurrencyCode = unofficialCurrencyCode;
        }

        /// <summary>
        /// A unique, Plaid-specific identifier for the security, used to associate securities with holdings. Like all Plaid identifiers, the `security_id` is case sensitive.
        /// </summary>
        [JsonProperty("security_id")]
        public string SecurityId { get; set; }

        /// <summary>
        /// 12-character ISIN, a globally unique securities identifier.
        /// </summary>
        [JsonProperty("isin", NullValueHandling = NullValueHandling.Include)]
        public string Isin { get; set; }

        /// <summary>
        /// 9-character CUSIP, an identifier assigned to North American securities.
        /// </summary>
        [JsonProperty("cusip", NullValueHandling = NullValueHandling.Include)]
        public string Cusip { get; set; }

        /// <summary>
        /// 7-character SEDOL, an identifier assigned to securities in the UK.
        /// </summary>
        [JsonProperty("sedol", NullValueHandling = NullValueHandling.Include)]
        public string Sedol { get; set; }

        /// <summary>
        /// An identifier given to the security by the institution
        /// </summary>
        [JsonProperty("institution_security_id", NullValueHandling = NullValueHandling.Include)]
        public string InstitutionSecurityId { get; set; }

        /// <summary>
        /// If `institution_security_id` is present, this field indicates the Plaid `institution_id` of the institution to whom the identifier belongs.
        /// </summary>
        [JsonProperty("institution_id", NullValueHandling = NullValueHandling.Include)]
        public string InstitutionId { get; set; }

        /// <summary>
        /// In certain cases, Plaid will provide the ID of another security whose performance resembles this security, typically when the original security has low volume, or when a private security can be modeled with a publicly traded security.
        /// </summary>
        [JsonProperty("proxy_security_id", NullValueHandling = NullValueHandling.Include)]
        public string ProxySecurityId { get; set; }

        /// <summary>
        /// A descriptive name for the security, suitable for display.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Include)]
        public string Name { get; set; }

        /// <summary>
        /// The security’s trading symbol for publicly traded securities, and otherwise a short identifier if available.
        /// </summary>
        [JsonProperty("ticker_symbol", NullValueHandling = NullValueHandling.Include)]
        public string TickerSymbol { get; set; }

        /// <summary>
        /// Indicates that a security is a highly liquid asset and can be treated like cash.
        /// </summary>
        [JsonProperty("is_cash_equivalent", NullValueHandling = NullValueHandling.Include)]
        public bool? IsCashEquivalent { get; set; }

        /// <summary>
        /// The security type of the holding. Valid security types are:
        /// `cash`: Cash, currency, and money market funds
        /// `derivative`: Options, warrants, and other derivative instruments
        /// `equity`: Domestic and foreign equities
        /// `etf`: Multi-asset exchange-traded investment funds
        /// `fixed income`: Bonds and certificates of deposit (CDs)
        /// `loan`: Loans and loan receivables.
        /// `mutual fund`: Open- and closed-end vehicles pooling funds of multiple investors.
        /// `other`: Unknown or other investment types
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Include)]
        public string Type { get; set; }

        /// <summary>
        /// Price of the security at the close of the previous trading session. `null` for non-public securities. If the security is a foreign currency or a cryptocurrency this field will be updated daily and will be priced in USD.
        /// </summary>
        [JsonProperty("close_price", NullValueHandling = NullValueHandling.Include)]
        public double? ClosePrice { get; set; }

        /// <summary>
        /// Date for which `close_price` is accurate. Always `null` if `close_price` is `null`.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("close_price_as_of", NullValueHandling = NullValueHandling.Include)]
        public DateTime? ClosePriceAsOf { get; set; }

        /// <summary>
        /// The ISO-4217 currency code of the price given. Always `null` if `unofficial_currency_code` is non-`null`.
        /// </summary>
        [JsonProperty("iso_currency_code", NullValueHandling = NullValueHandling.Include)]
        public string IsoCurrencyCode { get; set; }

        /// <summary>
        /// The unofficial currency code associated with the security. Always `null` if `iso_currency_code` is non-`null`. Unofficial currency codes are used for currencies that do not have official ISO currency codes, such as cryptocurrencies and the currencies of certain countries.
        /// See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `iso_currency_code`s.
        /// </summary>
        [JsonProperty("unofficial_currency_code", NullValueHandling = NullValueHandling.Include)]
        public string UnofficialCurrencyCode { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Security : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Security other &&
                (this.SecurityId == null && other.SecurityId == null ||
                 this.SecurityId?.Equals(other.SecurityId) == true) &&
                (this.Isin == null && other.Isin == null ||
                 this.Isin?.Equals(other.Isin) == true) &&
                (this.Cusip == null && other.Cusip == null ||
                 this.Cusip?.Equals(other.Cusip) == true) &&
                (this.Sedol == null && other.Sedol == null ||
                 this.Sedol?.Equals(other.Sedol) == true) &&
                (this.InstitutionSecurityId == null && other.InstitutionSecurityId == null ||
                 this.InstitutionSecurityId?.Equals(other.InstitutionSecurityId) == true) &&
                (this.InstitutionId == null && other.InstitutionId == null ||
                 this.InstitutionId?.Equals(other.InstitutionId) == true) &&
                (this.ProxySecurityId == null && other.ProxySecurityId == null ||
                 this.ProxySecurityId?.Equals(other.ProxySecurityId) == true) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.TickerSymbol == null && other.TickerSymbol == null ||
                 this.TickerSymbol?.Equals(other.TickerSymbol) == true) &&
                (this.IsCashEquivalent == null && other.IsCashEquivalent == null ||
                 this.IsCashEquivalent?.Equals(other.IsCashEquivalent) == true) &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true) &&
                (this.ClosePrice == null && other.ClosePrice == null ||
                 this.ClosePrice?.Equals(other.ClosePrice) == true) &&
                (this.ClosePriceAsOf == null && other.ClosePriceAsOf == null ||
                 this.ClosePriceAsOf?.Equals(other.ClosePriceAsOf) == true) &&
                (this.IsoCurrencyCode == null && other.IsoCurrencyCode == null ||
                 this.IsoCurrencyCode?.Equals(other.IsoCurrencyCode) == true) &&
                (this.UnofficialCurrencyCode == null && other.UnofficialCurrencyCode == null ||
                 this.UnofficialCurrencyCode?.Equals(other.UnofficialCurrencyCode) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"SecurityId = {this.SecurityId ?? "null"}");
            toStringOutput.Add($"Isin = {this.Isin ?? "null"}");
            toStringOutput.Add($"Cusip = {this.Cusip ?? "null"}");
            toStringOutput.Add($"Sedol = {this.Sedol ?? "null"}");
            toStringOutput.Add($"InstitutionSecurityId = {this.InstitutionSecurityId ?? "null"}");
            toStringOutput.Add($"InstitutionId = {this.InstitutionId ?? "null"}");
            toStringOutput.Add($"ProxySecurityId = {this.ProxySecurityId ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"TickerSymbol = {this.TickerSymbol ?? "null"}");
            toStringOutput.Add($"IsCashEquivalent = {(this.IsCashEquivalent == null ? "null" : this.IsCashEquivalent.ToString())}");
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"ClosePrice = {(this.ClosePrice == null ? "null" : this.ClosePrice.ToString())}");
            toStringOutput.Add($"ClosePriceAsOf = {(this.ClosePriceAsOf == null ? "null" : this.ClosePriceAsOf.ToString())}");
            toStringOutput.Add($"IsoCurrencyCode = {this.IsoCurrencyCode ?? "null"}");
            toStringOutput.Add($"UnofficialCurrencyCode = {this.UnofficialCurrencyCode ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}