// <copyright file="SecurityOverride.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// SecurityOverride.
    /// </summary>
    public class SecurityOverride
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecurityOverride"/> class.
        /// </summary>
        public SecurityOverride()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SecurityOverride"/> class.
        /// </summary>
        /// <param name="isin">isin.</param>
        /// <param name="cusip">cusip.</param>
        /// <param name="sedol">sedol.</param>
        /// <param name="name">name.</param>
        /// <param name="tickerSymbol">ticker_symbol.</param>
        /// <param name="currency">currency.</param>
        public SecurityOverride(
            string isin = null,
            string cusip = null,
            string sedol = null,
            string name = null,
            string tickerSymbol = null,
            string currency = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Isin = isin;
            this.Cusip = cusip;
            this.Sedol = sedol;
            this.Name = name;
            this.TickerSymbol = tickerSymbol;
            this.Currency = currency;
        }

        /// <summary>
        /// 12-character ISIN, a globally unique securities identifier.
        /// </summary>
        [JsonProperty("isin", NullValueHandling = NullValueHandling.Ignore)]
        public string Isin { get; set; }

        /// <summary>
        /// 9-character CUSIP, an identifier assigned to North American securities.
        /// </summary>
        [JsonProperty("cusip", NullValueHandling = NullValueHandling.Ignore)]
        public string Cusip { get; set; }

        /// <summary>
        /// 7-character SEDOL, an identifier assigned to securities in the UK.
        /// </summary>
        [JsonProperty("sedol", NullValueHandling = NullValueHandling.Ignore)]
        public string Sedol { get; set; }

        /// <summary>
        /// A descriptive name for the security, suitable for display.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// The security’s trading symbol for publicly traded securities, and otherwise a short identifier if available.
        /// </summary>
        [JsonProperty("ticker_symbol", NullValueHandling = NullValueHandling.Ignore)]
        public string TickerSymbol { get; set; }

        /// <summary>
        /// Either a valid `iso_currency_code` or `unofficial_currency_code`
        /// </summary>
        [JsonProperty("currency", NullValueHandling = NullValueHandling.Ignore)]
        public string Currency { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SecurityOverride : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is SecurityOverride other &&
                (this.Isin == null && other.Isin == null ||
                 this.Isin?.Equals(other.Isin) == true) &&
                (this.Cusip == null && other.Cusip == null ||
                 this.Cusip?.Equals(other.Cusip) == true) &&
                (this.Sedol == null && other.Sedol == null ||
                 this.Sedol?.Equals(other.Sedol) == true) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.TickerSymbol == null && other.TickerSymbol == null ||
                 this.TickerSymbol?.Equals(other.TickerSymbol) == true) &&
                (this.Currency == null && other.Currency == null ||
                 this.Currency?.Equals(other.Currency) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Isin = {this.Isin ?? "null"}");
            toStringOutput.Add($"Cusip = {this.Cusip ?? "null"}");
            toStringOutput.Add($"Sedol = {this.Sedol ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"TickerSymbol = {this.TickerSymbol ?? "null"}");
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}