// <copyright file="StandaloneAccountType.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// StandaloneAccountType.
    /// </summary>
    public class StandaloneAccountType
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StandaloneAccountType"/> class.
        /// </summary>
        public StandaloneAccountType()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StandaloneAccountType"/> class.
        /// </summary>
        /// <param name="depository">depository.</param>
        /// <param name="credit">credit.</param>
        /// <param name="loan">loan.</param>
        /// <param name="investment">investment.</param>
        /// <param name="other">other.</param>
        public StandaloneAccountType(
            Models.DepositoryAccount depository,
            Models.CreditAccount credit,
            Models.LoanAccount loan,
            Models.InvestmentAccountSubtype investment,
            string other)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Depository = depository;
            this.Credit = credit;
            this.Loan = loan;
            this.Investment = investment;
            this.Other = other;
        }

        /// <summary>
        /// An account type holding cash, in which funds are deposited. Supported products for `depository` accounts are: Auth, Balance, Transactions, Identity, Payment Initiation, and Assets.
        /// </summary>
        [JsonProperty("depository")]
        public Models.DepositoryAccount Depository { get; set; }

        /// <summary>
        /// A credit card type account. Supported products for `credit` accounts are: Balance, Transactions, Identity, and Liabilities.
        /// </summary>
        [JsonProperty("credit")]
        public Models.CreditAccount Credit { get; set; }

        /// <summary>
        /// A loan type account. Supported products for `loan` accounts are: Balance, Liabilities, and Transactions.
        /// </summary>
        [JsonProperty("loan")]
        public Models.LoanAccount Loan { get; set; }

        /// <summary>
        /// An investment account. Supported products for `investment` accounts are: Balance and Investments.
        /// </summary>
        [JsonProperty("investment")]
        public Models.InvestmentAccountSubtype Investment { get; set; }

        /// <summary>
        /// Other or unknown account type. Supported products for `other` accounts are: Balance, Transactions, Identity, and Assets.
        /// </summary>
        [JsonProperty("other")]
        public string Other { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"StandaloneAccountType : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is StandaloneAccountType other &&
                (this.Depository == null && other.Depository == null ||
                 this.Depository?.Equals(other.Depository) == true) &&
                (this.Credit == null && other.Credit == null ||
                 this.Credit?.Equals(other.Credit) == true) &&
                (this.Loan == null && other.Loan == null ||
                 this.Loan?.Equals(other.Loan) == true) &&
                (this.Investment == null && other.Investment == null ||
                 this.Investment?.Equals(other.Investment) == true) &&
                (this.Other == null && other.Other == null ||
                 this.Other?.Equals(other.Other) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Depository = {(this.Depository == null ? "null" : this.Depository.ToString())}");
            toStringOutput.Add($"Credit = {(this.Credit == null ? "null" : this.Credit.ToString())}");
            toStringOutput.Add($"Loan = {(this.Loan == null ? "null" : this.Loan.ToString())}");
            toStringOutput.Add($"Investment = {(this.Investment == null ? "null" : this.Investment.ToString())}");
            toStringOutput.Add($"Other = {this.Other ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}