// <copyright file="Status3.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// Status3.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum Status3
    {
        /// <summary>
        /// PaymentStatusInputNeeded.
        /// </summary>
        [EnumMember(Value = "PAYMENT_STATUS_INPUT_NEEDED")]
        PaymentStatusInputNeeded,

        /// <summary>
        /// PaymentStatusProcessing.
        /// </summary>
        [EnumMember(Value = "PAYMENT_STATUS_PROCESSING")]
        PaymentStatusProcessing,

        /// <summary>
        /// PaymentStatusInitiated.
        /// </summary>
        [EnumMember(Value = "PAYMENT_STATUS_INITIATED")]
        PaymentStatusInitiated,

        /// <summary>
        /// PaymentStatusCompleted.
        /// </summary>
        [EnumMember(Value = "PAYMENT_STATUS_COMPLETED")]
        PaymentStatusCompleted,

        /// <summary>
        /// PaymentStatusInsufficientFunds.
        /// </summary>
        [EnumMember(Value = "PAYMENT_STATUS_INSUFFICIENT_FUNDS")]
        PaymentStatusInsufficientFunds,

        /// <summary>
        /// PaymentStatusFailed.
        /// </summary>
        [EnumMember(Value = "PAYMENT_STATUS_FAILED")]
        PaymentStatusFailed,

        /// <summary>
        /// PaymentStatusBlocked.
        /// </summary>
        [EnumMember(Value = "PAYMENT_STATUS_BLOCKED")]
        PaymentStatusBlocked,

        /// <summary>
        /// PaymentStatusUnknown.
        /// </summary>
        [EnumMember(Value = "PAYMENT_STATUS_UNKNOWN")]
        PaymentStatusUnknown,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}