// <copyright file="Status.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// Status.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum Status
    {
        /// <summary>
        /// Healthy.
        /// </summary>
        [EnumMember(Value = "HEALTHY")]
        Healthy,

        /// <summary>
        /// Degraded.
        /// </summary>
        [EnumMember(Value = "DEGRADED")]
        Degraded,

        /// <summary>
        /// Down.
        /// </summary>
        [EnumMember(Value = "DOWN")]
        Down,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}