// <copyright file="TransferCreateRequest.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// TransferCreateRequest.
    /// </summary>
    public class TransferCreateRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string originationAccountId;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "origination_account_id", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="TransferCreateRequest"/> class.
        /// </summary>
        public TransferCreateRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransferCreateRequest"/> class.
        /// </summary>
        /// <param name="idempotencyKey">idempotency_key.</param>
        /// <param name="accessToken">access_token.</param>
        /// <param name="accountId">account_id.</param>
        /// <param name="authorizationId">authorization_id.</param>
        /// <param name="type">type.</param>
        /// <param name="network">network.</param>
        /// <param name="amount">amount.</param>
        /// <param name="description">description.</param>
        /// <param name="achClass">ach_class.</param>
        /// <param name="user">user.</param>
        /// <param name="clientId">client_id.</param>
        /// <param name="secret">secret.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="originationAccountId">origination_account_id.</param>
        public TransferCreateRequest(
            string idempotencyKey,
            string accessToken,
            string accountId,
            string authorizationId,
            Models.TransferType1 type,
            Models.TransferNetwork network,
            string amount,
            string description,
            Models.AchClass achClass,
            Models.TransferUserInRequest user,
            string clientId = null,
            string secret = null,
            Dictionary<string, string> metadata = null,
            string originationAccountId = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ClientId = clientId;
            this.Secret = secret;
            this.IdempotencyKey = idempotencyKey;
            this.AccessToken = accessToken;
            this.AccountId = accountId;
            this.AuthorizationId = authorizationId;
            this.Type = type;
            this.Network = network;
            this.Amount = amount;
            this.Description = description;
            this.AchClass = achClass;
            this.User = user;
            this.Metadata = metadata;

            if (originationAccountId != null)
            {
                this.OriginationAccountId = originationAccountId;
            }
        }

        /// <summary>
        /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
        /// </summary>
        [JsonProperty("client_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ClientId { get; set; }

        /// <summary>
        /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
        /// </summary>
        [JsonProperty("secret", NullValueHandling = NullValueHandling.Ignore)]
        public string Secret { get; set; }

        /// <summary>
        /// A random key provided by the client, per unique transfer. Maximum of 50 characters.
        /// The API supports idempotency for safely retrying requests without accidentally performing the same operation twice. For example, if a request to create a transfer fails due to a network connection error, you can retry the request with the same idempotency key to guarantee that only a single transfer is created.
        /// </summary>
        [JsonProperty("idempotency_key")]
        public string IdempotencyKey { get; set; }

        /// <summary>
        /// The Plaid `access_token` for the account that will be debited or credited.
        /// </summary>
        [JsonProperty("access_token")]
        public string AccessToken { get; set; }

        /// <summary>
        /// The Plaid `account_id` for the account that will be debited or credited.
        /// </summary>
        [JsonProperty("account_id")]
        public string AccountId { get; set; }

        /// <summary>
        /// Plaid’s unique identifier for a transfer authorization.
        /// </summary>
        [JsonProperty("authorization_id")]
        public string AuthorizationId { get; set; }

        /// <summary>
        /// The type of transfer. This will be either `debit` or `credit`.  A `debit` indicates a transfer of money into the origination account; a `credit` indicates a transfer of money out of the origination account.
        /// </summary>
        [JsonProperty("type")]
        public Models.TransferType1 Type { get; set; }

        /// <summary>
        /// The network or rails used for the transfer. Valid options are `ach` or `same-day-ach`.
        /// </summary>
        [JsonProperty("network")]
        public Models.TransferNetwork Network { get; set; }

        /// <summary>
        /// The amount of the transfer (decimal string with two digits of precision e.g. “10.00”).
        /// </summary>
        [JsonProperty("amount")]
        public string Amount { get; set; }

        /// <summary>
        /// The transfer description. Maximum of 10 characters.
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; }

        /// <summary>
        /// Specifies the use case of the transfer.  Required for transfers on an ACH network.
        /// `"arc"` - Accounts Receivable Entry
        /// `"cbr`" - Cross Border Entry
        /// `"ccd"` - Corporate Credit or Debit - fund transfer between two corporate bank accounts
        /// `"cie"` - Customer Initiated Entry
        /// `"cor"` - Automated Notification of Change
        /// `"ctx"` - Corporate Trade Exchange
        /// `"iat"` - International
        /// `"mte"` - Machine Transfer Entry
        /// `"pbr"` - Cross Border Entry
        /// `"pop"` - Point-of-Purchase Entry
        /// `"pos"` - Point-of-Sale Entry
        /// `"ppd"` - Prearranged Payment or Deposit - the transfer is part of a pre-existing relationship with a consumer, eg. bill payment
        /// `"rck"` - Re-presented Check Entry
        /// `"tel"` - Telephone-Initiated Entry
        /// `"web"` - Internet-Initiated Entry - debits from a consumer’s account where their authorization is obtained over the Internet
        /// </summary>
        [JsonProperty("ach_class")]
        public Models.AchClass AchClass { get; set; }

        /// <summary>
        /// The legal name and other information for the account holder.
        /// </summary>
        [JsonProperty("user")]
        public Models.TransferUserInRequest User { get; set; }

        /// <summary>
        /// The Metadata object is a mapping of client-provided string fields to any string value. The following limitations apply:
        /// - The JSON values must be Strings (no nested JSON objects allowed)
        /// - Only ASCII characters may be used
        /// - Maximum of 50 key/value pairs
        /// - Maximum key length of 40 characters
        /// - Maximum value length of 500 characters
        /// </summary>
        [JsonProperty("metadata", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// Plaid’s unique identifier for the origination account for this transfer. If you have more than one origination account, this value must be specified.
        /// </summary>
        [JsonProperty("origination_account_id")]
        public string OriginationAccountId
        {
            get
            {
                return this.originationAccountId;
            }

            set
            {
                this.shouldSerialize["origination_account_id"] = true;
                this.originationAccountId = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TransferCreateRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetOriginationAccountId()
        {
            this.shouldSerialize["origination_account_id"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeOriginationAccountId()
        {
            return this.shouldSerialize["origination_account_id"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TransferCreateRequest other &&
                (this.ClientId == null && other.ClientId == null ||
                 this.ClientId?.Equals(other.ClientId) == true) &&
                (this.Secret == null && other.Secret == null ||
                 this.Secret?.Equals(other.Secret) == true) &&
                (this.IdempotencyKey == null && other.IdempotencyKey == null ||
                 this.IdempotencyKey?.Equals(other.IdempotencyKey) == true) &&
                (this.AccessToken == null && other.AccessToken == null ||
                 this.AccessToken?.Equals(other.AccessToken) == true) &&
                (this.AccountId == null && other.AccountId == null ||
                 this.AccountId?.Equals(other.AccountId) == true) &&
                (this.AuthorizationId == null && other.AuthorizationId == null ||
                 this.AuthorizationId?.Equals(other.AuthorizationId) == true) &&
                (this.Type.Equals(other.Type)) &&
                (this.Network.Equals(other.Network)) &&
                (this.Amount == null && other.Amount == null ||
                 this.Amount?.Equals(other.Amount) == true) &&
                (this.Description == null && other.Description == null ||
                 this.Description?.Equals(other.Description) == true) &&
                (this.AchClass.Equals(other.AchClass)) &&
                (this.User == null && other.User == null ||
                 this.User?.Equals(other.User) == true) &&
                (this.Metadata == null && other.Metadata == null ||
                 this.Metadata?.Equals(other.Metadata) == true) &&
                (this.OriginationAccountId == null && other.OriginationAccountId == null ||
                 this.OriginationAccountId?.Equals(other.OriginationAccountId) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ClientId = {this.ClientId ?? "null"}");
            toStringOutput.Add($"Secret = {this.Secret ?? "null"}");
            toStringOutput.Add($"IdempotencyKey = {this.IdempotencyKey ?? "null"}");
            toStringOutput.Add($"AccessToken = {this.AccessToken ?? "null"}");
            toStringOutput.Add($"AccountId = {this.AccountId ?? "null"}");
            toStringOutput.Add($"AuthorizationId = {this.AuthorizationId ?? "null"}");
            toStringOutput.Add($"Type = {this.Type}");
            toStringOutput.Add($"Network = {this.Network}");
            toStringOutput.Add($"Amount = {this.Amount ?? "null"}");
            toStringOutput.Add($"Description = {this.Description ?? "null"}");
            toStringOutput.Add($"AchClass = {this.AchClass}");
            toStringOutput.Add($"User = {(this.User == null ? "null" : this.User.ToString())}");
            toStringOutput.Add($"Metadata = {(this.Metadata == null ? "null" : this.Metadata.ToString())}");
            toStringOutput.Add($"OriginationAccountId = {this.OriginationAccountId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}