// <copyright file="TransactionsGetResponse.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// TransactionsGetResponse.
    /// </summary>
    public class TransactionsGetResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsGetResponse"/> class.
        /// </summary>
        public TransactionsGetResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsGetResponse"/> class.
        /// </summary>
        /// <param name="accounts">accounts.</param>
        /// <param name="transactions">transactions.</param>
        /// <param name="totalTransactions">total_transactions.</param>
        /// <param name="item">item.</param>
        /// <param name="requestId">request_id.</param>
        public TransactionsGetResponse(
            List<Models.Account> accounts,
            List<Models.Transaction> transactions,
            int totalTransactions,
            Models.Item item,
            string requestId)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Accounts = accounts;
            this.Transactions = transactions;
            this.TotalTransactions = totalTransactions;
            this.Item = item;
            this.RequestId = requestId;
        }

        /// <summary>
        /// An array containing the `accounts` associated with the Item for which transactions are being returned. Each transaction can be mapped to its corresponding account via the `account_id` field.
        /// </summary>
        [JsonProperty("accounts")]
        public List<Models.Account> Accounts { get; set; }

        /// <summary>
        /// An array containing transactions from the account. Transactions are returned in reverse chronological order, with the most recent at the beginning of the array. The maximum number of transactions returned is determined by the `count` parameter.
        /// </summary>
        [JsonProperty("transactions")]
        public List<Models.Transaction> Transactions { get; set; }

        /// <summary>
        /// The total number of transactions available within the date range specified. If `total_transactions` is larger than the size of the `transactions` array, more transactions are available and can be fetched via manipulating the `offset` parameter.
        /// </summary>
        [JsonProperty("total_transactions")]
        public int TotalTransactions { get; set; }

        /// <summary>
        /// Metadata about the Item.
        /// </summary>
        [JsonProperty("item")]
        public Models.Item Item { get; set; }

        /// <summary>
        /// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
        /// </summary>
        [JsonProperty("request_id")]
        public string RequestId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TransactionsGetResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TransactionsGetResponse other &&
                (this.Accounts == null && other.Accounts == null ||
                 this.Accounts?.Equals(other.Accounts) == true) &&
                (this.Transactions == null && other.Transactions == null ||
                 this.Transactions?.Equals(other.Transactions) == true) &&
                (this.TotalTransactions.Equals(other.TotalTransactions)) &&
                (this.Item == null && other.Item == null ||
                 this.Item?.Equals(other.Item) == true) &&
                (this.RequestId == null && other.RequestId == null ||
                 this.RequestId?.Equals(other.RequestId) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Accounts = {(this.Accounts == null ? "null" : $"[{string.Join(", ", this.Accounts)} ]")}");
            toStringOutput.Add($"Transactions = {(this.Transactions == null ? "null" : $"[{string.Join(", ", this.Transactions)} ]")}");
            toStringOutput.Add($"TotalTransactions = {this.TotalTransactions}");
            toStringOutput.Add($"Item = {(this.Item == null ? "null" : this.Item.ToString())}");
            toStringOutput.Add($"RequestId = {this.RequestId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}