// <copyright file="TransferEvent.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// TransferEvent.
    /// </summary>
    public class TransferEvent
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransferEvent"/> class.
        /// </summary>
        public TransferEvent()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransferEvent"/> class.
        /// </summary>
        /// <param name="eventId">event_id.</param>
        /// <param name="timestamp">timestamp.</param>
        /// <param name="eventType">event_type.</param>
        /// <param name="accountId">account_id.</param>
        /// <param name="transferId">transfer_id.</param>
        /// <param name="transferType">transfer_type.</param>
        /// <param name="transferAmount">transfer_amount.</param>
        /// <param name="failureReason">failure_reason.</param>
        /// <param name="originationAccountId">origination_account_id.</param>
        public TransferEvent(
            int eventId,
            DateTime timestamp,
            Models.TransferEventType eventType,
            string accountId,
            string transferId,
            Models.TransferType1 transferType,
            string transferAmount,
            Models.TransferFailure failureReason,
            string originationAccountId = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.EventId = eventId;
            this.Timestamp = timestamp;
            this.EventType = eventType;
            this.AccountId = accountId;
            this.TransferId = transferId;
            this.OriginationAccountId = originationAccountId;
            this.TransferType = transferType;
            this.TransferAmount = transferAmount;
            this.FailureReason = failureReason;
        }

        /// <summary>
        /// Plaid’s unique identifier for this event. IDs are sequential unsigned 64-bit integers.
        /// </summary>
        [JsonProperty("event_id")]
        public int EventId { get; set; }

        /// <summary>
        /// The datetime when this event occurred. This will be of the form `2006-01-02T15:04:05Z`.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("timestamp")]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// The type of event that this transfer represents.
        /// `pending`: A new transfer was created; it is in the pending state.
        /// `cancelled`: The transfer was cancelled by the client.
        /// `failed`: The transfer failed, no funds were moved.
        /// `posted`: The transfer has been successfully submitted to the payment network.
        /// `reversed`: A posted transfer was reversed.
        /// </summary>
        [JsonProperty("event_type")]
        public Models.TransferEventType EventType { get; set; }

        /// <summary>
        /// The account ID associated with the transfer.
        /// </summary>
        [JsonProperty("account_id")]
        public string AccountId { get; set; }

        /// <summary>
        /// Plaid’s unique identifier for a transfer.
        /// </summary>
        [JsonProperty("transfer_id")]
        public string TransferId { get; set; }

        /// <summary>
        /// The ID of the origination account that this balance belongs to.
        /// </summary>
        [JsonProperty("origination_account_id", NullValueHandling = NullValueHandling.Include)]
        public string OriginationAccountId { get; set; }

        /// <summary>
        /// The type of transfer. This will be either `debit` or `credit`.  A `debit` indicates a transfer of money into the origination account; a `credit` indicates a transfer of money out of the origination account.
        /// </summary>
        [JsonProperty("transfer_type")]
        public Models.TransferType1 TransferType { get; set; }

        /// <summary>
        /// The amount of the transfer (decimal string with two digits of precision e.g. “10.00”).
        /// </summary>
        [JsonProperty("transfer_amount")]
        public string TransferAmount { get; set; }

        /// <summary>
        /// The failure reason if the type of this transfer is `"failed"` or `"reversed"`. Null value otherwise.
        /// </summary>
        [JsonProperty("failure_reason")]
        public Models.TransferFailure FailureReason { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TransferEvent : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TransferEvent other &&
                (this.EventId.Equals(other.EventId)) &&
                (this.Timestamp.Equals(other.Timestamp)) &&
                (this.EventType.Equals(other.EventType)) &&
                (this.AccountId == null && other.AccountId == null ||
                 this.AccountId?.Equals(other.AccountId) == true) &&
                (this.TransferId == null && other.TransferId == null ||
                 this.TransferId?.Equals(other.TransferId) == true) &&
                (this.OriginationAccountId == null && other.OriginationAccountId == null ||
                 this.OriginationAccountId?.Equals(other.OriginationAccountId) == true) &&
                (this.TransferType.Equals(other.TransferType)) &&
                (this.TransferAmount == null && other.TransferAmount == null ||
                 this.TransferAmount?.Equals(other.TransferAmount) == true) &&
                (this.FailureReason == null && other.FailureReason == null ||
                 this.FailureReason?.Equals(other.FailureReason) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"EventId = {this.EventId}");
            toStringOutput.Add($"Timestamp = {this.Timestamp}");
            toStringOutput.Add($"EventType = {this.EventType}");
            toStringOutput.Add($"AccountId = {this.AccountId ?? "null"}");
            toStringOutput.Add($"TransferId = {this.TransferId ?? "null"}");
            toStringOutput.Add($"OriginationAccountId = {this.OriginationAccountId ?? "null"}");
            toStringOutput.Add($"TransferType = {this.TransferType}");
            toStringOutput.Add($"TransferAmount = {this.TransferAmount ?? "null"}");
            toStringOutput.Add($"FailureReason = {(this.FailureReason == null ? "null" : this.FailureReason.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}