// <copyright file="TransferListRequest.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// TransferListRequest.
    /// </summary>
    public class TransferListRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private DateTime? startDate;
        private DateTime? endDate;
        private string originationAccountId;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "start_date", false },
            { "end_date", false },
            { "origination_account_id", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="TransferListRequest"/> class.
        /// </summary>
        public TransferListRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransferListRequest"/> class.
        /// </summary>
        /// <param name="clientId">client_id.</param>
        /// <param name="secret">secret.</param>
        /// <param name="startDate">start_date.</param>
        /// <param name="endDate">end_date.</param>
        /// <param name="count">count.</param>
        /// <param name="offset">offset.</param>
        /// <param name="originationAccountId">origination_account_id.</param>
        public TransferListRequest(
            string clientId = null,
            string secret = null,
            DateTime? startDate = null,
            DateTime? endDate = null,
            int? count = 25,
            int? offset = 0,
            string originationAccountId = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ClientId = clientId;
            this.Secret = secret;

            if (startDate != null)
            {
                this.StartDate = startDate;
            }

            if (endDate != null)
            {
                this.EndDate = endDate;
            }
            this.Count = count;
            this.Offset = offset;

            if (originationAccountId != null)
            {
                this.OriginationAccountId = originationAccountId;
            }
        }

        /// <summary>
        /// Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header or as part of a request body.
        /// </summary>
        [JsonProperty("client_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ClientId { get; set; }

        /// <summary>
        /// Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part of a request body.
        /// </summary>
        [JsonProperty("secret", NullValueHandling = NullValueHandling.Ignore)]
        public string Secret { get; set; }

        /// <summary>
        /// The start datetime of transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("start_date")]
        public DateTime? StartDate
        {
            get
            {
                return this.startDate;
            }

            set
            {
                this.shouldSerialize["start_date"] = true;
                this.startDate = value;
            }
        }

        /// <summary>
        /// The end datetime of transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("end_date")]
        public DateTime? EndDate
        {
            get
            {
                return this.endDate;
            }

            set
            {
                this.shouldSerialize["end_date"] = true;
                this.endDate = value;
            }
        }

        /// <summary>
        /// The maximum number of transfers to return.
        /// </summary>
        [JsonProperty("count", NullValueHandling = NullValueHandling.Ignore)]
        public int? Count { get; set; }

        /// <summary>
        /// The number of transfers to skip before returning results.
        /// </summary>
        [JsonProperty("offset", NullValueHandling = NullValueHandling.Ignore)]
        public int? Offset { get; set; }

        /// <summary>
        /// Filter transfers to only those originated through the specified origination account.
        /// </summary>
        [JsonProperty("origination_account_id")]
        public string OriginationAccountId
        {
            get
            {
                return this.originationAccountId;
            }

            set
            {
                this.shouldSerialize["origination_account_id"] = true;
                this.originationAccountId = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TransferListRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetStartDate()
        {
            this.shouldSerialize["start_date"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEndDate()
        {
            this.shouldSerialize["end_date"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetOriginationAccountId()
        {
            this.shouldSerialize["origination_account_id"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeStartDate()
        {
            return this.shouldSerialize["start_date"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEndDate()
        {
            return this.shouldSerialize["end_date"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeOriginationAccountId()
        {
            return this.shouldSerialize["origination_account_id"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TransferListRequest other &&
                (this.ClientId == null && other.ClientId == null ||
                 this.ClientId?.Equals(other.ClientId) == true) &&
                (this.Secret == null && other.Secret == null ||
                 this.Secret?.Equals(other.Secret) == true) &&
                (this.StartDate == null && other.StartDate == null ||
                 this.StartDate?.Equals(other.StartDate) == true) &&
                (this.EndDate == null && other.EndDate == null ||
                 this.EndDate?.Equals(other.EndDate) == true) &&
                (this.Count == null && other.Count == null ||
                 this.Count?.Equals(other.Count) == true) &&
                (this.Offset == null && other.Offset == null ||
                 this.Offset?.Equals(other.Offset) == true) &&
                (this.OriginationAccountId == null && other.OriginationAccountId == null ||
                 this.OriginationAccountId?.Equals(other.OriginationAccountId) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ClientId = {this.ClientId ?? "null"}");
            toStringOutput.Add($"Secret = {this.Secret ?? "null"}");
            toStringOutput.Add($"StartDate = {(this.StartDate == null ? "null" : this.StartDate.ToString())}");
            toStringOutput.Add($"EndDate = {(this.EndDate == null ? "null" : this.EndDate.ToString())}");
            toStringOutput.Add($"Count = {(this.Count == null ? "null" : this.Count.ToString())}");
            toStringOutput.Add($"Offset = {(this.Offset == null ? "null" : this.Offset.ToString())}");
            toStringOutput.Add($"OriginationAccountId = {this.OriginationAccountId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}