// <copyright file="Type5.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// Type5.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum Type5
    {
        /// <summary>
        /// Bonus.
        /// </summary>
        [EnumMember(Value = "bonus")]
        Bonus,

        /// <summary>
        /// Overtime.
        /// </summary>
        [EnumMember(Value = "overtime")]
        Overtime,

        /// <summary>
        /// Regular.
        /// </summary>
        [EnumMember(Value = "regular")]
        Regular,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}