// <copyright file="VerificationStatus3.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// VerificationStatus3.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum VerificationStatus3
    {
        /// <summary>
        /// VerificationStatusProcessingComplete.
        /// </summary>
        [EnumMember(Value = "VERIFICATION_STATUS_PROCESSING_COMPLETE")]
        VerificationStatusProcessingComplete,

        /// <summary>
        /// VerificationStatusDocumentRejected.
        /// </summary>
        [EnumMember(Value = "VERIFICATION_STATUS_DOCUMENT_REJECTED")]
        VerificationStatusDocumentRejected,

        /// <summary>
        /// VerificationStatusProcessingFailed.
        /// </summary>
        [EnumMember(Value = "VERIFICATION_STATUS_PROCESSING_FAILED")]
        VerificationStatusProcessingFailed,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}