// <copyright file="W2.cs" company="APIMatic">
// Plaid.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Plaid.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Plaid.Standard.Models
{
    /// <summary>
    /// W2.
    /// </summary>
    public class W2
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string taxYear;
        private string employerIdNumber;
        private string wagesTipsOtherComp;
        private string federalIncomeTaxWithheld;
        private string socialSecurityWages;
        private string socialSecurityTaxWithheld;
        private string medicareWagesAndTips;
        private string medicareTaxWithheld;
        private string socialSecurityTips;
        private string allocatedTips;
        private string box9;
        private string dependentCareBenefits;
        private string nonqualifiedPlans;
        private string statutoryEmployee;
        private string retirementPlan;
        private string thirdPartySickPay;
        private string other;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "tax_year", false },
            { "employer_id_number", false },
            { "wages_tips_other_comp", false },
            { "federal_income_tax_withheld", false },
            { "social_security_wages", false },
            { "social_security_tax_withheld", false },
            { "medicare_wages_and_tips", false },
            { "medicare_tax_withheld", false },
            { "social_security_tips", false },
            { "allocated_tips", false },
            { "box_9", false },
            { "dependent_care_benefits", false },
            { "nonqualified_plans", false },
            { "statutory_employee", false },
            { "retirement_plan", false },
            { "third_party_sick_pay", false },
            { "other", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="W2"/> class.
        /// </summary>
        public W2()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="W2"/> class.
        /// </summary>
        /// <param name="employer">employer.</param>
        /// <param name="employee">employee.</param>
        /// <param name="taxYear">tax_year.</param>
        /// <param name="employerIdNumber">employer_id_number.</param>
        /// <param name="wagesTipsOtherComp">wages_tips_other_comp.</param>
        /// <param name="federalIncomeTaxWithheld">federal_income_tax_withheld.</param>
        /// <param name="socialSecurityWages">social_security_wages.</param>
        /// <param name="socialSecurityTaxWithheld">social_security_tax_withheld.</param>
        /// <param name="medicareWagesAndTips">medicare_wages_and_tips.</param>
        /// <param name="medicareTaxWithheld">medicare_tax_withheld.</param>
        /// <param name="socialSecurityTips">social_security_tips.</param>
        /// <param name="allocatedTips">allocated_tips.</param>
        /// <param name="box9">box_9.</param>
        /// <param name="dependentCareBenefits">dependent_care_benefits.</param>
        /// <param name="nonqualifiedPlans">nonqualified_plans.</param>
        /// <param name="box12">box_12.</param>
        /// <param name="statutoryEmployee">statutory_employee.</param>
        /// <param name="retirementPlan">retirement_plan.</param>
        /// <param name="thirdPartySickPay">third_party_sick_pay.</param>
        /// <param name="other">other.</param>
        /// <param name="stateAndLocalWages">state_and_local_wages.</param>
        public W2(
            Models.Employer2 employer = null,
            Models.Employee employee = null,
            string taxYear = null,
            string employerIdNumber = null,
            string wagesTipsOtherComp = null,
            string federalIncomeTaxWithheld = null,
            string socialSecurityWages = null,
            string socialSecurityTaxWithheld = null,
            string medicareWagesAndTips = null,
            string medicareTaxWithheld = null,
            string socialSecurityTips = null,
            string allocatedTips = null,
            string box9 = null,
            string dependentCareBenefits = null,
            string nonqualifiedPlans = null,
            List<Models.W2Box12> box12 = null,
            string statutoryEmployee = null,
            string retirementPlan = null,
            string thirdPartySickPay = null,
            string other = null,
            List<Models.W2StateAndLocalWages> stateAndLocalWages = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Employer = employer;
            this.Employee = employee;

            if (taxYear != null)
            {
                this.TaxYear = taxYear;
            }

            if (employerIdNumber != null)
            {
                this.EmployerIdNumber = employerIdNumber;
            }

            if (wagesTipsOtherComp != null)
            {
                this.WagesTipsOtherComp = wagesTipsOtherComp;
            }

            if (federalIncomeTaxWithheld != null)
            {
                this.FederalIncomeTaxWithheld = federalIncomeTaxWithheld;
            }

            if (socialSecurityWages != null)
            {
                this.SocialSecurityWages = socialSecurityWages;
            }

            if (socialSecurityTaxWithheld != null)
            {
                this.SocialSecurityTaxWithheld = socialSecurityTaxWithheld;
            }

            if (medicareWagesAndTips != null)
            {
                this.MedicareWagesAndTips = medicareWagesAndTips;
            }

            if (medicareTaxWithheld != null)
            {
                this.MedicareTaxWithheld = medicareTaxWithheld;
            }

            if (socialSecurityTips != null)
            {
                this.SocialSecurityTips = socialSecurityTips;
            }

            if (allocatedTips != null)
            {
                this.AllocatedTips = allocatedTips;
            }

            if (box9 != null)
            {
                this.Box9 = box9;
            }

            if (dependentCareBenefits != null)
            {
                this.DependentCareBenefits = dependentCareBenefits;
            }

            if (nonqualifiedPlans != null)
            {
                this.NonqualifiedPlans = nonqualifiedPlans;
            }
            this.Box12 = box12;

            if (statutoryEmployee != null)
            {
                this.StatutoryEmployee = statutoryEmployee;
            }

            if (retirementPlan != null)
            {
                this.RetirementPlan = retirementPlan;
            }

            if (thirdPartySickPay != null)
            {
                this.ThirdPartySickPay = thirdPartySickPay;
            }

            if (other != null)
            {
                this.Other = other;
            }
            this.StateAndLocalWages = stateAndLocalWages;
        }

        /// <summary>
        /// Gets or sets Employer.
        /// </summary>
        [JsonProperty("employer", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Employer2 Employer { get; set; }

        /// <summary>
        /// Data about the employee.
        /// </summary>
        [JsonProperty("employee", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Employee Employee { get; set; }

        /// <summary>
        /// The tax year of the W2 document.
        /// </summary>
        [JsonProperty("tax_year")]
        public string TaxYear
        {
            get
            {
                return this.taxYear;
            }

            set
            {
                this.shouldSerialize["tax_year"] = true;
                this.taxYear = value;
            }
        }

        /// <summary>
        /// An employee identification number or EIN.
        /// </summary>
        [JsonProperty("employer_id_number")]
        public string EmployerIdNumber
        {
            get
            {
                return this.employerIdNumber;
            }

            set
            {
                this.shouldSerialize["employer_id_number"] = true;
                this.employerIdNumber = value;
            }
        }

        /// <summary>
        /// Wages from tips and other compensation.
        /// </summary>
        [JsonProperty("wages_tips_other_comp")]
        public string WagesTipsOtherComp
        {
            get
            {
                return this.wagesTipsOtherComp;
            }

            set
            {
                this.shouldSerialize["wages_tips_other_comp"] = true;
                this.wagesTipsOtherComp = value;
            }
        }

        /// <summary>
        /// Federal income tax withheld for the tax year.
        /// </summary>
        [JsonProperty("federal_income_tax_withheld")]
        public string FederalIncomeTaxWithheld
        {
            get
            {
                return this.federalIncomeTaxWithheld;
            }

            set
            {
                this.shouldSerialize["federal_income_tax_withheld"] = true;
                this.federalIncomeTaxWithheld = value;
            }
        }

        /// <summary>
        /// Wages from social security.
        /// </summary>
        [JsonProperty("social_security_wages")]
        public string SocialSecurityWages
        {
            get
            {
                return this.socialSecurityWages;
            }

            set
            {
                this.shouldSerialize["social_security_wages"] = true;
                this.socialSecurityWages = value;
            }
        }

        /// <summary>
        /// Social security tax withheld for the tax year.
        /// </summary>
        [JsonProperty("social_security_tax_withheld")]
        public string SocialSecurityTaxWithheld
        {
            get
            {
                return this.socialSecurityTaxWithheld;
            }

            set
            {
                this.shouldSerialize["social_security_tax_withheld"] = true;
                this.socialSecurityTaxWithheld = value;
            }
        }

        /// <summary>
        /// Wages and tips from medicare.
        /// </summary>
        [JsonProperty("medicare_wages_and_tips")]
        public string MedicareWagesAndTips
        {
            get
            {
                return this.medicareWagesAndTips;
            }

            set
            {
                this.shouldSerialize["medicare_wages_and_tips"] = true;
                this.medicareWagesAndTips = value;
            }
        }

        /// <summary>
        /// Medicare tax withheld for the tax year.
        /// </summary>
        [JsonProperty("medicare_tax_withheld")]
        public string MedicareTaxWithheld
        {
            get
            {
                return this.medicareTaxWithheld;
            }

            set
            {
                this.shouldSerialize["medicare_tax_withheld"] = true;
                this.medicareTaxWithheld = value;
            }
        }

        /// <summary>
        /// Tips from social security.
        /// </summary>
        [JsonProperty("social_security_tips")]
        public string SocialSecurityTips
        {
            get
            {
                return this.socialSecurityTips;
            }

            set
            {
                this.shouldSerialize["social_security_tips"] = true;
                this.socialSecurityTips = value;
            }
        }

        /// <summary>
        /// Allocated tips.
        /// </summary>
        [JsonProperty("allocated_tips")]
        public string AllocatedTips
        {
            get
            {
                return this.allocatedTips;
            }

            set
            {
                this.shouldSerialize["allocated_tips"] = true;
                this.allocatedTips = value;
            }
        }

        /// <summary>
        /// Contents from box 9 on the W2.
        /// </summary>
        [JsonProperty("box_9")]
        public string Box9
        {
            get
            {
                return this.box9;
            }

            set
            {
                this.shouldSerialize["box_9"] = true;
                this.box9 = value;
            }
        }

        /// <summary>
        /// Dependent care benefits.
        /// </summary>
        [JsonProperty("dependent_care_benefits")]
        public string DependentCareBenefits
        {
            get
            {
                return this.dependentCareBenefits;
            }

            set
            {
                this.shouldSerialize["dependent_care_benefits"] = true;
                this.dependentCareBenefits = value;
            }
        }

        /// <summary>
        /// Nonqualified plans.
        /// </summary>
        [JsonProperty("nonqualified_plans")]
        public string NonqualifiedPlans
        {
            get
            {
                return this.nonqualifiedPlans;
            }

            set
            {
                this.shouldSerialize["nonqualified_plans"] = true;
                this.nonqualifiedPlans = value;
            }
        }

        /// <summary>
        /// Gets or sets Box12.
        /// </summary>
        [JsonProperty("box_12", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.W2Box12> Box12 { get; set; }

        /// <summary>
        /// Statutory employee.
        /// </summary>
        [JsonProperty("statutory_employee")]
        public string StatutoryEmployee
        {
            get
            {
                return this.statutoryEmployee;
            }

            set
            {
                this.shouldSerialize["statutory_employee"] = true;
                this.statutoryEmployee = value;
            }
        }

        /// <summary>
        /// Retirement plan.
        /// </summary>
        [JsonProperty("retirement_plan")]
        public string RetirementPlan
        {
            get
            {
                return this.retirementPlan;
            }

            set
            {
                this.shouldSerialize["retirement_plan"] = true;
                this.retirementPlan = value;
            }
        }

        /// <summary>
        /// Third party sick pay.
        /// </summary>
        [JsonProperty("third_party_sick_pay")]
        public string ThirdPartySickPay
        {
            get
            {
                return this.thirdPartySickPay;
            }

            set
            {
                this.shouldSerialize["third_party_sick_pay"] = true;
                this.thirdPartySickPay = value;
            }
        }

        /// <summary>
        /// Other.
        /// </summary>
        [JsonProperty("other")]
        public string Other
        {
            get
            {
                return this.other;
            }

            set
            {
                this.shouldSerialize["other"] = true;
                this.other = value;
            }
        }

        /// <summary>
        /// Gets or sets StateAndLocalWages.
        /// </summary>
        [JsonProperty("state_and_local_wages", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.W2StateAndLocalWages> StateAndLocalWages { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"W2 : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTaxYear()
        {
            this.shouldSerialize["tax_year"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEmployerIdNumber()
        {
            this.shouldSerialize["employer_id_number"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWagesTipsOtherComp()
        {
            this.shouldSerialize["wages_tips_other_comp"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFederalIncomeTaxWithheld()
        {
            this.shouldSerialize["federal_income_tax_withheld"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSocialSecurityWages()
        {
            this.shouldSerialize["social_security_wages"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSocialSecurityTaxWithheld()
        {
            this.shouldSerialize["social_security_tax_withheld"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMedicareWagesAndTips()
        {
            this.shouldSerialize["medicare_wages_and_tips"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMedicareTaxWithheld()
        {
            this.shouldSerialize["medicare_tax_withheld"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSocialSecurityTips()
        {
            this.shouldSerialize["social_security_tips"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAllocatedTips()
        {
            this.shouldSerialize["allocated_tips"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetBox9()
        {
            this.shouldSerialize["box_9"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDependentCareBenefits()
        {
            this.shouldSerialize["dependent_care_benefits"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetNonqualifiedPlans()
        {
            this.shouldSerialize["nonqualified_plans"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetStatutoryEmployee()
        {
            this.shouldSerialize["statutory_employee"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetRetirementPlan()
        {
            this.shouldSerialize["retirement_plan"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetThirdPartySickPay()
        {
            this.shouldSerialize["third_party_sick_pay"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetOther()
        {
            this.shouldSerialize["other"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTaxYear()
        {
            return this.shouldSerialize["tax_year"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEmployerIdNumber()
        {
            return this.shouldSerialize["employer_id_number"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWagesTipsOtherComp()
        {
            return this.shouldSerialize["wages_tips_other_comp"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFederalIncomeTaxWithheld()
        {
            return this.shouldSerialize["federal_income_tax_withheld"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSocialSecurityWages()
        {
            return this.shouldSerialize["social_security_wages"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSocialSecurityTaxWithheld()
        {
            return this.shouldSerialize["social_security_tax_withheld"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMedicareWagesAndTips()
        {
            return this.shouldSerialize["medicare_wages_and_tips"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMedicareTaxWithheld()
        {
            return this.shouldSerialize["medicare_tax_withheld"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSocialSecurityTips()
        {
            return this.shouldSerialize["social_security_tips"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAllocatedTips()
        {
            return this.shouldSerialize["allocated_tips"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeBox9()
        {
            return this.shouldSerialize["box_9"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDependentCareBenefits()
        {
            return this.shouldSerialize["dependent_care_benefits"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeNonqualifiedPlans()
        {
            return this.shouldSerialize["nonqualified_plans"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeStatutoryEmployee()
        {
            return this.shouldSerialize["statutory_employee"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeRetirementPlan()
        {
            return this.shouldSerialize["retirement_plan"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeThirdPartySickPay()
        {
            return this.shouldSerialize["third_party_sick_pay"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeOther()
        {
            return this.shouldSerialize["other"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is W2 other &&
                (this.Employer == null && other.Employer == null ||
                 this.Employer?.Equals(other.Employer) == true) &&
                (this.Employee == null && other.Employee == null ||
                 this.Employee?.Equals(other.Employee) == true) &&
                (this.TaxYear == null && other.TaxYear == null ||
                 this.TaxYear?.Equals(other.TaxYear) == true) &&
                (this.EmployerIdNumber == null && other.EmployerIdNumber == null ||
                 this.EmployerIdNumber?.Equals(other.EmployerIdNumber) == true) &&
                (this.WagesTipsOtherComp == null && other.WagesTipsOtherComp == null ||
                 this.WagesTipsOtherComp?.Equals(other.WagesTipsOtherComp) == true) &&
                (this.FederalIncomeTaxWithheld == null && other.FederalIncomeTaxWithheld == null ||
                 this.FederalIncomeTaxWithheld?.Equals(other.FederalIncomeTaxWithheld) == true) &&
                (this.SocialSecurityWages == null && other.SocialSecurityWages == null ||
                 this.SocialSecurityWages?.Equals(other.SocialSecurityWages) == true) &&
                (this.SocialSecurityTaxWithheld == null && other.SocialSecurityTaxWithheld == null ||
                 this.SocialSecurityTaxWithheld?.Equals(other.SocialSecurityTaxWithheld) == true) &&
                (this.MedicareWagesAndTips == null && other.MedicareWagesAndTips == null ||
                 this.MedicareWagesAndTips?.Equals(other.MedicareWagesAndTips) == true) &&
                (this.MedicareTaxWithheld == null && other.MedicareTaxWithheld == null ||
                 this.MedicareTaxWithheld?.Equals(other.MedicareTaxWithheld) == true) &&
                (this.SocialSecurityTips == null && other.SocialSecurityTips == null ||
                 this.SocialSecurityTips?.Equals(other.SocialSecurityTips) == true) &&
                (this.AllocatedTips == null && other.AllocatedTips == null ||
                 this.AllocatedTips?.Equals(other.AllocatedTips) == true) &&
                (this.Box9 == null && other.Box9 == null ||
                 this.Box9?.Equals(other.Box9) == true) &&
                (this.DependentCareBenefits == null && other.DependentCareBenefits == null ||
                 this.DependentCareBenefits?.Equals(other.DependentCareBenefits) == true) &&
                (this.NonqualifiedPlans == null && other.NonqualifiedPlans == null ||
                 this.NonqualifiedPlans?.Equals(other.NonqualifiedPlans) == true) &&
                (this.Box12 == null && other.Box12 == null ||
                 this.Box12?.Equals(other.Box12) == true) &&
                (this.StatutoryEmployee == null && other.StatutoryEmployee == null ||
                 this.StatutoryEmployee?.Equals(other.StatutoryEmployee) == true) &&
                (this.RetirementPlan == null && other.RetirementPlan == null ||
                 this.RetirementPlan?.Equals(other.RetirementPlan) == true) &&
                (this.ThirdPartySickPay == null && other.ThirdPartySickPay == null ||
                 this.ThirdPartySickPay?.Equals(other.ThirdPartySickPay) == true) &&
                (this.Other == null && other.Other == null ||
                 this.Other?.Equals(other.Other) == true) &&
                (this.StateAndLocalWages == null && other.StateAndLocalWages == null ||
                 this.StateAndLocalWages?.Equals(other.StateAndLocalWages) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Employer = {(this.Employer == null ? "null" : this.Employer.ToString())}");
            toStringOutput.Add($"Employee = {(this.Employee == null ? "null" : this.Employee.ToString())}");
            toStringOutput.Add($"TaxYear = {this.TaxYear ?? "null"}");
            toStringOutput.Add($"EmployerIdNumber = {this.EmployerIdNumber ?? "null"}");
            toStringOutput.Add($"WagesTipsOtherComp = {this.WagesTipsOtherComp ?? "null"}");
            toStringOutput.Add($"FederalIncomeTaxWithheld = {this.FederalIncomeTaxWithheld ?? "null"}");
            toStringOutput.Add($"SocialSecurityWages = {this.SocialSecurityWages ?? "null"}");
            toStringOutput.Add($"SocialSecurityTaxWithheld = {this.SocialSecurityTaxWithheld ?? "null"}");
            toStringOutput.Add($"MedicareWagesAndTips = {this.MedicareWagesAndTips ?? "null"}");
            toStringOutput.Add($"MedicareTaxWithheld = {this.MedicareTaxWithheld ?? "null"}");
            toStringOutput.Add($"SocialSecurityTips = {this.SocialSecurityTips ?? "null"}");
            toStringOutput.Add($"AllocatedTips = {this.AllocatedTips ?? "null"}");
            toStringOutput.Add($"Box9 = {this.Box9 ?? "null"}");
            toStringOutput.Add($"DependentCareBenefits = {this.DependentCareBenefits ?? "null"}");
            toStringOutput.Add($"NonqualifiedPlans = {this.NonqualifiedPlans ?? "null"}");
            toStringOutput.Add($"Box12 = {(this.Box12 == null ? "null" : $"[{string.Join(", ", this.Box12)} ]")}");
            toStringOutput.Add($"StatutoryEmployee = {this.StatutoryEmployee ?? "null"}");
            toStringOutput.Add($"RetirementPlan = {this.RetirementPlan ?? "null"}");
            toStringOutput.Add($"ThirdPartySickPay = {this.ThirdPartySickPay ?? "null"}");
            toStringOutput.Add($"Other = {this.Other ?? "null"}");
            toStringOutput.Add($"StateAndLocalWages = {(this.StateAndLocalWages == null ? "null" : $"[{string.Join(", ", this.StateAndLocalWages)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}