using System.Collections.Generic;
using System.Text.Json.Serialization;
using ThePlaidApi.Core.Models;
using ThePlaidApi.Models.Enums;

namespace ThePlaidApi.Models;

/// <summary>
/// Data to use to set values of test accounts. Some values cannot be specified in the schema and will instead will be calculated from other test data in order to achieve more consistent, realistic test data.
/// </summary>
public record OverrideAccounts
{
    /// <summary>
    /// <c>investment:</c> Investment account
    /// <para>
    /// <c>credit:</c> Credit card
    /// </para>
    /// <para>
    /// <c>depository:</c> Depository account
    /// </para>
    /// <para>
    /// <c>loan:</c> Loan account
    /// </para>
    /// <para>
    /// <c>payroll:</c> Payroll acccount
    /// </para>
    /// <para>
    /// <c>other:</c> Non-specified account type
    /// </para>
    /// <para>
    /// See the <see href="https://plaid.com/docs/api/accounts#account-type-schema">Account type schema</see> for a full listing of account types and corresponding subtypes.
    /// </para>
    /// </summary>
    [JsonPropertyName("type")]
    public required OverrideAccountType Type { get; init; }

    /// <summary>
    /// See the <see href="https://plaid.com/docs/api/accounts/#account-type-schema">Account type schema</see> for a full listing of account types and corresponding subtypes.
    /// </summary>
    [JsonPropertyName("subtype")]
    public required AccountSubtype Subtype { get; init; }

    /// <summary>
    /// If provided, the account will start with this amount as the current balance.
    /// </summary>
    [JsonPropertyName("starting_balance")]
    public required double StartingBalance { get; init; }

    /// <summary>
    /// If provided, the account will always have this amount as its  available balance, regardless of current balance or changes in transactions over time.
    /// </summary>
    [JsonPropertyName("force_available_balance")]
    public required double ForceAvailableBalance { get; init; }

    /// <summary>
    /// ISO-4217 currency code. If provided, the account will be denominated in the given currency. Transactions will also be in this currency by default.
    /// </summary>
    [JsonPropertyName("currency")]
    public required string Currency { get; init; }

    /// <summary>
    /// Allows specifying the metadata of the test account
    /// </summary>
    [JsonPropertyName("meta")]
    public required Meta Meta { get; init; }

    /// <summary>
    /// Account and bank identifier number data used to configure the test account. All values are optional.
    /// </summary>
    [JsonPropertyName("numbers")]
    public required Numbers Numbers { get; init; }

    /// <summary>
    /// Specify the list of transactions on the account.
    /// </summary>
    [JsonPropertyName("transactions")]
    public required IReadOnlyList<TransactionOverride> Transactions { get; init; }

    /// <summary>
    /// Specify the holdings on the account.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("holdings")]
    public HoldingsOverride? Holdings { get; init; }

    /// <summary>
    /// Specify the list of investments transactions on the account.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("investment_transactions")]
    public InvestmentsTransactionsOverride? InvestmentTransactions { get; init; }

    /// <summary>
    /// Data about the owner or owners of an account. Any fields not specified will be filled in with default Sandbox information.
    /// </summary>
    [JsonPropertyName("identity")]
    public required OwnerOverride Identity { get; init; }

    /// <summary>
    /// Used to configure Sandbox test data for the Liabilities product
    /// </summary>
    [JsonPropertyName("liability")]
    public required LiabilityOverride Liability { get; init; }

    /// <summary>
    /// The <c>inflow_model</c> allows you to model a test account that receives regular income or make regular payments on a loan. Any transactions generated by the <c>inflow_model</c> will appear in addition to randomly generated test data or transactions specified by <c>override_accounts</c>.
    /// </summary>
    [JsonPropertyName("inflow_model")]
    public required InflowModel InflowModel { get; init; }

    /// <summary>
    /// Specify payroll data on the account.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("income")]
    public IncomeOverride? Income { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
