using System.Text.Json.Serialization;
using ThePlaidApi.Core.Models;

namespace ThePlaidApi.Models;

/// <summary>
/// Information describing the intent of the transaction. Most relevant for personal finance use cases, but not limited to such use cases. The field is currently in beta.
/// <para>
/// The complete category can be generated by concatenating primary and detailed categories.
/// </para>
/// <para>
/// This feature is currently in beta – to request access, contact transactions-feedback@plaid.com.
/// </para>
/// </summary>
public record PersonalFinanceCategory
{
    /// <summary>
    /// A high level category that communicates the broad category of the transaction.
    /// </summary>
    [JsonPropertyName("primary")]
    public required string Primary { get; init; }

    /// <summary>
    /// Provides additional granularity to the primary categorization.
    /// </summary>
    [JsonPropertyName("detailed")]
    public required string Detailed { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
